print error if fai-setup fails

diff --git a/files/etc/rc.local/FAISERVER b/files/etc/rc.local/FAISERVER
--- a/files/etc/rc.local/FAISERVER
+++ b/files/etc/rc.local/FAISERVER
@@ -32,7 +32,15 @@ curl -fs 'http://192.168.33.250:3142/acng-report.html?doImport=Start+Import&calc
 
 # setup the FAI server, including creating the nfsroot
 fai-setup -B /var/tmp/base.tar.xz -v 2>&1
-[ $? -eq 0 ] && rm /var/tmp/base.tar.xz
+if [ $? -eq 0 ]; then
+    rm /var/tmp/base.tar.xz
+else
+    echo "=================================" >/dev/console
+    echo "ERROR: Setting up the FAI install server failed!" >/dev/console
+    echo "=================================" >/dev/console
+    sleep 7
+    exit 99
+fi
 
 # create default pxelinux boot configuration
 fai-chboot -o default
