use $* instead of $@

diff --git a/bin/fai b/bin/fai
--- a/bin/fai
+++ b/bin/fai
@@ -48,7 +48,7 @@ fdie() {
     local e=$1   # first parameter is the exit code
     shift
 
-    echo "$@" >&2 # print error message
+    echo "$*" >&2 # print error message
     exit $e
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
diff --git a/bin/fai-cd b/bin/fai-cd
--- a/bin/fai-cd
+++ b/bin/fai-cd
@@ -76,7 +76,7 @@ die() {
     local e=$1   # first parameter is the exit code
     shift
 
-    echo -e "ERROR: $@" >&2   # print error message
+    echo -e "ERROR: $*" >&2   # print error message
     exit $e
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - -
diff --git a/bin/fai-diskimage b/bin/fai-diskimage
--- a/bin/fai-diskimage
+++ b/bin/fai-diskimage
@@ -12,7 +12,7 @@ die() {
     local e=$1   # first parameter is the exit code
     shift
 
-    echo "ERROR: $@" >&2   # print error message
+    echo "ERROR: $*" >&2   # print error message
     exit $e
 }
 
@@ -133,7 +133,7 @@ while true ; do
             shift
             break ;;
          *)
-            die 1 "$0: command line parsing error ! $@" >&2 ;;
+            die 1 "$0: command line parsing error ! $*" >&2 ;;
     esac
 done
 
diff --git a/bin/fai-mirror b/bin/fai-mirror
--- a/bin/fai-mirror
+++ b/bin/fai-mirror
@@ -43,7 +43,7 @@ die() {
     local e=$1   # first parameter is the exit code
     shift
 
-    echo "$@" >&2 # print error message
+    echo "$*" >&2 # print error message
     exit $e
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
diff --git a/bin/ftar b/bin/ftar
--- a/bin/ftar
+++ b/bin/ftar
@@ -32,7 +32,7 @@ die() {
     local e=$1   # first parameter is the exit code
     shift
 
-    echo "ftar: $@" >&2 # print error message
+    echo "ftar: $*" >&2 # print error message
     exit $e
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
