check if targetdir is specified when doing dirinst

diff --git a/bin/fai b/bin/fai
--- a/bin/fai
+++ b/bin/fai
@@ -193,6 +193,11 @@ done
 [ "$2" ] && targetdir=$2 # only used for dirinst
 
 if [ X$action = Xdirinst ]; then
+    if [ -z "$targetdir" ]; then
+	echo "Please specify a target directory. Aborted"
+	exit 3
+    fi
+
     eval `grep NFSROOT= /etc/fai/make-fai-nfsroot.conf`
     export NFSROOT
     export FAI_ROOT=$targetdir
