move fdie() into fai, move reading of subroutines back last position

diff --git a/bin/fai b/bin/fai
--- a/bin/fai
+++ b/bin/fai
@@ -39,6 +39,16 @@ export romountopt="-o async,noatime,nolock,ro,actimeo=1800"
 export STOP_ON_ERROR=700
 export faimond=0
 export renewclass=0
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+fdie() {
+
+    local e=$1   # first parameter is the exit code
+    shift
+
+    echo "$@" >&2 # print error message
+    exit $e
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 fai_init() {
 
@@ -61,6 +71,9 @@ fai_init() {
         MNTPOINT=/media/mirror
         FAI_CONFIG_SRC="file://$FAI"   # on a fai-cd the config space is already available
     fi
+
+    # read subroutine definitions
+    . /usr/lib/fai/subroutines
 
     [ -f "$stamp" ] && {
        echo -n "$0 already running or was aborted before. PID: " >&2
@@ -166,9 +179,6 @@ fstart() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main routine
-
-# read subroutine definitions
-. /usr/lib/fai/subroutines
 
 # Parse commandline options
 TEMP=$(getopt -o s:u:Nhvc:C: --long cspace:,hostname:,new,help,verbose,class:,cfdir: -n "$0" -- "$@")
