convert tab to space

diff --git a/bin/fai b/bin/fai
--- a/bin/fai
+++ b/bin/fai
@@ -1,5 +1,5 @@
 #!/bin/bash
-# $Id$
+
 #*********************************************************************
 #
 # fai -- main installation script executed after booting
@@ -55,11 +55,11 @@ fai_init() {
     unset cspace
 
     if [ -f /etc/RUNNING_FROM_FAICD ]; then   # we are booting from fai cd
-	umount /initrd
-	romountopt=
-	FAI_DEBMIRROR="--bind /media/mirror"
-	MNTPOINT=/media/mirror
-	FAI_CONFIG_SRC="file://$FAI"   # on a fai-cd the config space is already available
+        umount /initrd
+        romountopt=
+        FAI_DEBMIRROR="--bind /media/mirror"
+        MNTPOINT=/media/mirror
+        FAI_CONFIG_SRC="file://$FAI"   # on a fai-cd the config space is already available
     fi
 
     # read subroutine definitions
@@ -90,26 +90,26 @@ fai_init() {
     fi
 
     if [ $do_init_tasks -eq 1 ]; then
-	eval_cmdline
-	[ -d /sys/kernel ] || mount -t sysfs sysfs /sys
-	# we really need to start udev
-	[ -x /etc/init.d/udev ] && [ X$UPSTART_JOB != Xfai ] && /etc/init.d/udev start
-	mkdir -p /var/run/network /dev/shm/network # when using initrd kernels
-	ifup lo
-	[ -x /sbin/portmap ] && /sbin/portmap
-	[ -x /sbin/rpcbind ] && /sbin/rpcbind
+        eval_cmdline
+        [ -d /sys/kernel ] || mount -t sysfs sysfs /sys
+        # we really need to start udev
+        [ -x /etc/init.d/udev ] && [ X$UPSTART_JOB != Xfai ] && /etc/init.d/udev start
+        mkdir -p /var/run/network /dev/shm/network # when using initrd kernels
+        ifup lo
+        [ -x /sbin/portmap ] && /sbin/portmap
+        [ -x /sbin/rpcbind ] && /sbin/rpcbind
 
-	# NFS v4 support
-	sed -i -e '/Nobody-/d' /etc/idmapd.conf
-	ainsl -v /etc/idmapd.conf 'Nobody-User = root'
-	ainsl -v /etc/idmapd.conf 'Nobody-Group = root'
-	rpc.statd # idmapd needs this
-	rpc.idmapd -C # idmapd needs option -v or rpc.statd must be running. Otherwise the next command (like mount, ls -l) hangs.
+        # NFS v4 support
+        sed -i -e '/Nobody-/d' /etc/idmapd.conf
+        ainsl -v /etc/idmapd.conf 'Nobody-User = root'
+        ainsl -v /etc/idmapd.conf 'Nobody-Group = root'
+        rpc.statd # idmapd needs this
+        rpc.idmapd -C # idmapd needs option -v or rpc.statd must be running. Otherwise the next command (like mount, ls -l) hangs.
 
-	if grep -wq devpts /proc/mounts; then
-	    mount -t devpts devpts /dev/pts
-	fi
-	cat /proc/kmsg >/dev/tty4 &
+        if grep -wq devpts /proc/mounts; then
+            mount -t devpts devpts /dev/pts
+        fi
+        cat /proc/kmsg >/dev/tty4 &
     fi
 
     # since HOSTNAME may change define classes now, so we can call hooks before fai-class is called
@@ -122,17 +122,17 @@ fai_init() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 usage() {
     cat <<-EOF
-	fai $FAI_VERSION. Copyright (C) 1999-2011 Thomas Lange
-	Usage: $0 [options] [action]
+        fai $FAI_VERSION. Copyright (C) 1999-2011 Thomas Lange
+        Usage: $0 [options] [action]
 
-	Options:
-	   -v|--verbose         display more information during the update
-	   -h|--help            display this help message
-	   -N|--new             renew list of classes
-	   -c|--class           comma separated list of classes
-	   -C|--cfdir CFDIR     Use CFDIR for  reading the config files
-	   -s|--cspace CSDIR    URI of the configuration space
-	   -u|--hostname HNAME  set hostname to be used
+        Options:
+           -v|--verbose         display more information during the update
+           -h|--help            display this help message
+           -N|--new             renew list of classes
+           -c|--class           comma separated list of classes
+           -C|--cfdir CFDIR     Use CFDIR for  reading the config files
+           -s|--cspace CSDIR    URI of the configuration space
+           -u|--hostname HNAME  set hostname to be used
 
 EOF
     exit 0
@@ -149,8 +149,8 @@ fstart() {
     # if the config space is a local directory, reset $FAI
     local method=$(expr match "$FAI_CONFIG_SRC" '\([^+]*\).*://')
     if [ $method = "file" ]; then
-	local localpath=$(expr match "$FAI_CONFIG_SRC" '.*://\(/.*\)')
-	export FAI=$localpath
+        local localpath=$(expr match "$FAI_CONFIG_SRC" '.*://\(/.*\)')
+        export FAI=$localpath
     fi
     task setup
     task defclass
@@ -172,30 +172,30 @@ unset TEMP
 while true ; do
     case "$1" in
         -h|--help)
-	    usage ;;
-	-v|--verbose)
-	    export verbose=1
-	    shift ;;
-	-N|--new)
-	    renewclass=1
-	    shift ;;
-	-C|--cfdir)
-	    cfdir=$2
-	    shift 2 ;;
-	-c|--class)
-	    if [ $renewclass -eq 1 ]; then
-		echo "You can't use -c|--classes and -N|--new at the same time." >&2
-		exit 9
-	    fi
-	    export cmdlineclasses=$2
-	    cmdlineclasses=${cmdlineclasses//,/ }
-	    shift 2 ;;
-	-s|--cspace)
-	    cspace=$2
-	    shift 2 ;;
-	-u|--hostname)
-	    export newhostname=$2
-	    shift 2 ;;
+            usage ;;
+        -v|--verbose)
+            export verbose=1
+            shift ;;
+        -N|--new)
+            renewclass=1
+            shift ;;
+        -C|--cfdir)
+            cfdir=$2
+            shift 2 ;;
+        -c|--class)
+            if [ $renewclass -eq 1 ]; then
+                echo "You can't use -c|--classes and -N|--new at the same time." >&2
+                exit 9
+            fi
+            export cmdlineclasses=$2
+            cmdlineclasses=${cmdlineclasses//,/ }
+            shift 2 ;;
+        -s|--cspace)
+            cspace=$2
+            shift 2 ;;
+        -u|--hostname)
+            export newhostname=$2
+            shift 2 ;;
         --) 
             shift
             break ;;
@@ -222,12 +222,12 @@ export FAI_ETC_DIR
 
 if [ X$action = Xdirinstall ]; then
     if [ -z "$FAI_ROOT" ]; then
-	echo "Please specify a target directory. Aborted" >&2
-	exit 3
+        echo "Please specify a target directory. Aborted" >&2
+        exit 3
     fi
     if [ $renewclass -eq 0 -a -z "$cmdlineclasses" ]; then
-	echo "Please use -c or -N. Aborted" >&2
-	exit 4
+        echo "Please use -c or -N. Aborted" >&2
+        exit 4
     fi
 
     # two lines taken from task_dirinstall
@@ -237,15 +237,15 @@ if [ X$action = Xdirinstall ]; then
     # check if target directory is mounted with bad options
     fs=$(df -P $FAI_ROOT | tail -1 | awk '{print $6}')
     if mount | grep "on $fs " |  awk '{print $6}' | egrep -q "nosuid|nodev"; then
-	echo "Target directory is mounted using nosuid or nodev. Aborting" >&2
-	exit 5
+        echo "Target directory is mounted using nosuid or nodev. Aborting" >&2
+        exit 5
     fi
     unset fs
 
     if [ ! -e $FAI_ETC_DIR/nfsroot.conf ]; then
-	echo "$FAI_ETC_DIR/nfsroot.conf not found." >&2
-	echo "You may want to install the package fai-server" >&2
-	exit 7
+        echo "$FAI_ETC_DIR/nfsroot.conf not found." >&2
+        echo "You may want to install the package fai-server" >&2
+        exit 7
     fi
     export NFSROOT=$(source $FAI_ETC_DIR/nfsroot.conf; echo $NFSROOT)
     export FAI_DEBOOTSTRAP=$(source $FAI_ETC_DIR/nfsroot.conf; echo $FAI_DEBOOTSTRAP)
@@ -273,8 +273,8 @@ if [ $do_init_tasks -eq 1 ]; then
     for word in $(cat /proc/cmdline) ; do
         case $word in
             hostname=*)
-	    HOSTNAME=${word#*hostname=}
-	    ;;
+            HOSTNAME=${word#*hostname=}
+            ;;
         esac
     done
     unset word
diff --git a/bin/fai-cd b/bin/fai-cd
--- a/bin/fai-cd
+++ b/bin/fai-cd
@@ -50,12 +50,12 @@ hidedirs="/usr/share/locale /usr/share/doc /var/lib/apt /var/cache/apt /usr/shar
 usage() {
 
     cat <<-EOF
-	fai-cd Copyright (C) 2004-2012 Thomas Lange
+        fai-cd Copyright (C) 2004-2012 Thomas Lange
 
-	Usage: fai-cd [OPTIONS] -m MIRRORDIR ISONAME
-	Usage: fai-cd [OPTIONS] -B ISONAME
-	Create a FAI CD, a bootable CD that performs the FAI.
-	Read the man pages pages fai-cd(8).
+        Usage: fai-cd [OPTIONS] -m MIRRORDIR ISONAME
+        Usage: fai-cd [OPTIONS] -B ISONAME
+        Create a FAI CD, a bootable CD that performs the FAI.
+        Read the man pages pages fai-cd(8).
 EOF
 exit 0
 }
@@ -73,35 +73,35 @@ create_grub1_image() {
 
     mkdir -p $tmp/boot/grub $nfsrootdir/live/filesystem.dir
     if [ -f $NFSROOT/usr/lib/grub/*-pc/stage2_eltorito ]; then
-	echo "preparing grub1 eltorito boot loader using NFSROOT"
-	[ -d $NFSROOT/usr/lib/grub ] && cp -p $NFSROOT/usr/lib/grub/*-pc/stage2_eltorito $tmp/boot/grub/
-	[ -d $NFSROOT/usr/lib/grub ] && cp -p $NFSROOT/usr/lib/grub/*-pc/stage{1,2} $tmp/boot/grub/
+        echo "preparing grub1 eltorito boot loader using NFSROOT"
+        [ -d $NFSROOT/usr/lib/grub ] && cp -p $NFSROOT/usr/lib/grub/*-pc/stage2_eltorito $tmp/boot/grub/
+        [ -d $NFSROOT/usr/lib/grub ] && cp -p $NFSROOT/usr/lib/grub/*-pc/stage{1,2} $tmp/boot/grub/
     else
-	# if grub1 is not available in NFSROOT, we download the package based on the current
-	# sources.list, unpack and use these files for further processing
-	# this does not work if file: URI's are used in sources.lst
-	apt-get -d install --reinstall grub >/dev/null
-	grubPackage=`ls -rt /var/cache/apt/archives/grub_*|tail -1`
-	if [ -z "$grubPackage" ]; then
-	    die 21 "Downloading grub failed."
-	fi
+        # if grub1 is not available in NFSROOT, we download the package based on the current
+        # sources.list, unpack and use these files for further processing
+        # this does not work if file: URI's are used in sources.lst
+        apt-get -d install --reinstall grub >/dev/null
+        grubPackage=`ls -rt /var/cache/apt/archives/grub_*|tail -1`
+        if [ -z "$grubPackage" ]; then
+            die 21 "Downloading grub failed."
+        fi
 
-	GRUBDIR=$tmp/grubPackage
-	echo "no grub1 installation found in NFSROOT, using downloaded $grubPackage"
-	mkdir -p $GRUBDIR
-	dpkg -x $grubPackage $GRUBDIR
-	cp -p $GRUBDIR/usr/lib/grub/*-pc/stage2_eltorito $tmp/boot/grub/
-	cp -p $GRUBDIR/usr/lib/grub/*-pc/stage{1,2} $tmp/boot/grub/
-	rm -rf $GRUBDIR
+        GRUBDIR=$tmp/grubPackage
+        echo "no grub1 installation found in NFSROOT, using downloaded $grubPackage"
+        mkdir -p $GRUBDIR
+        dpkg -x $grubPackage $GRUBDIR
+        cp -p $GRUBDIR/usr/lib/grub/*-pc/stage2_eltorito $tmp/boot/grub/
+        cp -p $GRUBDIR/usr/lib/grub/*-pc/stage{1,2} $tmp/boot/grub/
+        rm -rf $GRUBDIR
     fi
     cp $grub_config $tmp/boot/grub/menu.lst
     # insert date into grub menu
     if [ $bootonly -eq 1 ]; then
-	echo "Using kernel version $kernelversion"
-	perl -pi -e "s/_VERSIONSTRING_/Kernel : $kernelversion/" $tmp/boot/grub/menu.lst
-	perl -pi -e "s#_NFSROOT_#nfsroot=$servernfsroot#"        $tmp/boot/grub/menu.lst
+        echo "Using kernel version $kernelversion"
+        perl -pi -e "s/_VERSIONSTRING_/Kernel : $kernelversion/" $tmp/boot/grub/menu.lst
+        perl -pi -e "s#_NFSROOT_#nfsroot=$servernfsroot#"        $tmp/boot/grub/menu.lst
     else
-	perl -pi -e "s/_VERSIONSTRING_/   $isoversion     /" $tmp/boot/grub/menu.lst
+        perl -pi -e "s/_VERSIONSTRING_/   $isoversion     /" $tmp/boot/grub/menu.lst
     fi
     cp -p $NFSROOT/boot/vmlinuz-$kernelversion $tmp/boot/vmlinuz
     cp -p $NFSROOT/boot/initrd.img-$kernelversion $tmp/boot/initrd.img
@@ -113,35 +113,35 @@ create_grub2_image() {
 
     mkdir -p $tmp/boot/grub $nfsrootdir/live/filesystem.dir $NFSROOT/boot/grub
     if [ -f $NFSROOT/boot/grub/core.img ]; then
-	echo "preparing grub2 eltorito.img using existing core.img from NFSROOT"
-	cp $NFSROOT/boot/grub/core.img $tmp/boot/grub
-	MODULEBASE=$NFSROOT/usr/lib/grub/
+        echo "preparing grub2 eltorito.img using existing core.img from NFSROOT"
+        cp $NFSROOT/boot/grub/core.img $tmp/boot/grub
+        MODULEBASE=$NFSROOT/usr/lib/grub/
     elif [ -f $NFSROOT/usr/lib/grub/i386-pc/cdboot.img ]; then
-	echo "preparing grub2 eltorito.img creating core.img in NFSROOT"
+        echo "preparing grub2 eltorito.img creating core.img in NFSROOT"
         if chroot $NFSROOT /usr/bin/grub-mkimage --help | grep -q -- --format ; then
-	    chroot $NFSROOT /usr/bin/grub-mkimage -d /usr/lib/grub/i386-pc -o /boot/grub/core.img biosdisk iso9660 --format=i386-pc
+            chroot $NFSROOT /usr/bin/grub-mkimage -d /usr/lib/grub/i386-pc -o /boot/grub/core.img biosdisk iso9660 --format=i386-pc
         else
-	    chroot $NFSROOT /usr/bin/grub-mkimage -d /usr/lib/grub/i386-pc -o /boot/grub/core.img biosdisk iso9660
+            chroot $NFSROOT /usr/bin/grub-mkimage -d /usr/lib/grub/i386-pc -o /boot/grub/core.img biosdisk iso9660
         fi
-	cp $NFSROOT/boot/grub/core.img $tmp/boot/grub
-	MODULEBASE=$NFSROOT/usr/lib/grub/
+        cp $NFSROOT/boot/grub/core.img $tmp/boot/grub
+        MODULEBASE=$NFSROOT/usr/lib/grub/
     else
-	echo "no grub2 installation found in NFSROOT, using downloaded $grubPackage"
-	apt-get -y -d install --reinstall grub-pc >/dev/null
-	grubPackage=`ls -rt /var/cache/apt/archives/grub-pc*|tail -1`
-	if [ -z "$grubPackage" ]; then
-	    die 22 "Downloading grub2 failed."
-	fi
-	GRUBDIR=$tmp/grubPackage
-	mkdir -p $GRUBDIR
-	dpkg -x $grubPackage $GRUBDIR
-	cd $GRUBDIR
-	if ./usr/bin/grub-mkimage --help | grep -q -- --format ; then
-	    ./usr/bin/grub-mkimage -d usr/lib/grub/*-pc -o $tmp/boot/grub/core.img biosdisk iso9660 --format=i386-pc
-	else
-	    ./usr/bin/grub-mkimage -d usr/lib/grub/*-pc -o $tmp/boot/grub/core.img biosdisk iso9660
-	fi
-	MODULEBASE=$GRUBDIR/usr/lib/grub/
+        echo "no grub2 installation found in NFSROOT, using downloaded $grubPackage"
+        apt-get -y -d install --reinstall grub-pc >/dev/null
+        grubPackage=`ls -rt /var/cache/apt/archives/grub-pc*|tail -1`
+        if [ -z "$grubPackage" ]; then
+            die 22 "Downloading grub2 failed."
+        fi
+        GRUBDIR=$tmp/grubPackage
+        mkdir -p $GRUBDIR
+        dpkg -x $grubPackage $GRUBDIR
+        cd $GRUBDIR
+        if ./usr/bin/grub-mkimage --help | grep -q -- --format ; then
+            ./usr/bin/grub-mkimage -d usr/lib/grub/*-pc -o $tmp/boot/grub/core.img biosdisk iso9660 --format=i386-pc
+        else
+            ./usr/bin/grub-mkimage -d usr/lib/grub/*-pc -o $tmp/boot/grub/core.img biosdisk iso9660
+        fi
+        MODULEBASE=$GRUBDIR/usr/lib/grub/
     fi
     for a in $MODULEBASE/*-pc/{*.mod,efiemu??.o,cdboot.img,command.lst,moddep.lst,fs.lst,handler.lst,parttool.lst}; do
         [[ -e $a ]] && cp $a $tmp/boot/grub
@@ -160,19 +160,19 @@ create_grub2_image() {
 provide_memtest_boot_option() {
 
     if [ -f $NFSROOT/boot/memtest86+.bin ]; then
-	cp $NFSROOT/boot/memtest86+.bin $tmp/boot
+        cp $NFSROOT/boot/memtest86+.bin $tmp/boot
     elif [ -f /boot/memtest86+.bin ]; then
-	cp /boot/memtest86+.bin $tmp/boot
+        cp /boot/memtest86+.bin $tmp/boot
     else
-	echo "no memtest86+.bin found, omit memtest boot option"
-	return
+        echo "no memtest86+.bin found, omit memtest boot option"
+        return
     fi
     
     if [ "$grub_version" -eq 1 ]; then
         cat >> $tmp/boot/grub/menu.lst <<EOF
 
 title           memtest86+
-root		(cd)
+root            (cd)
 kernel          /boot/memtest86+.bin
 quiet
 EOF
@@ -193,10 +193,10 @@ customize_nfsroot() {
 
     mkdir $tmp/empty
     for d in $hidedirs; do
-	if [ -d $nfsrootdir/$d ]; then
-	    [ "$debug" ] && echo "hiding $d"
-	    mount --bind $tmp/empty $nfsrootdir/$d
-	fi
+        if [ -d $nfsrootdir/$d ]; then
+            [ "$debug" ] && echo "hiding $d"
+            mount --bind $tmp/empty $nfsrootdir/$d
+        fi
     done
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -204,10 +204,10 @@ unhide_dirs() {
 
     set +e
     for d in $hidedirs; do
-	if [ -d $nfsrootdir/$d ]; then
-	    [ "$debug" ] && echo "disclosing $d"
-	    umount $nfsrootdir/$d 2>/dev/null
-	fi
+        if [ -d $nfsrootdir/$d ]; then
+            [ "$debug" ] && echo "disclosing $d"
+            umount $nfsrootdir/$d 2>/dev/null
+        fi
     done
     set -e
 }
@@ -218,7 +218,7 @@ umount_dirs() {
     local d
     local dirs="boot $FAI media/mirror etc/apt/sources.list"
     for d in $dirs; do
-	umount $nfsrootdir/$d 2>/dev/null
+        umount $nfsrootdir/$d 2>/dev/null
     done
     rm -f $nfsrootdir/etc/RUNNING_FROM_FAICD
     [ -d $nfsrootdir ] && umount $nfsrootdir
@@ -227,7 +227,7 @@ umount_dirs() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - -
 sleep_now() {
 
-	sleep 6666 || true
+        sleep 6666 || true
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - -
 mkiso() {
@@ -248,13 +248,13 @@ mkusb(){
     # TODO: If usbdir is a device (matches /dev/) mount it
     [ -d $usbdir ] || die 17 "$usbdir does not exist."
     if [ $rsync -eq 1 ]; then
-	echo "Syncing FAI data to USB device $usbdir"
-	rsync --delete -avW $tmp/boot $usbdir || true
-	[ -d $tmp/live ] && rsync --delete -avW $tmp/live $usbdir || true
+        echo "Syncing FAI data to USB device $usbdir"
+        rsync --delete -avW $tmp/boot $usbdir || true
+        [ -d $tmp/live ] && rsync --delete -avW $tmp/live $usbdir || true
     else
-	echo "Writing FAI data to USB device $usbdir"
-	cp -a $tmp/boot $usbdir 2>/dev/null || true
-	[ -d $tmp/live ] && cp -a $tmp/live $usbdir 2>/dev/null || true
+        echo "Writing FAI data to USB device $usbdir"
+        cp -a $tmp/boot $usbdir 2>/dev/null || true
+        [ -d $tmp/live ] && cp -a $tmp/live $usbdir 2>/dev/null || true
     fi
     echo $isoversion > $usbdir/.FAI-CD-VERSION
 
@@ -266,10 +266,10 @@ mkusb(){
     usbdev=$(echo $rootpartition | sed -e 's/,[[:digit:]]//')
     echo "Root partition is $rootpartition, device is: $usbdev"
     if [ -n "$rootpartition" -a -n "$usbdev" ]; then
-	echo "Installing grub."
-	echo -e "root $rootpartition\n setup $usbdev" | grub --batch >/dev/null
+        echo "Installing grub."
+        echo -e "root $rootpartition\n setup $usbdev" | grub --batch >/dev/null
     else
-	echo "Device could not be detemined. Installing grub will be skipped."
+        echo "Device could not be detemined. Installing grub will be skipped."
     fi
 
     elif [ "$grub_version" -eq 2 ]; then
@@ -309,19 +309,19 @@ EOF
     [ -z "$dists" ] && die 19 "No suitable Packages file found in mirror."
 
     for i in $dists ; do
-	comp=$(find $mirrordir/dists/$i -maxdepth 2 -type d -name "binary-*" | \
+        comp=$(find $mirrordir/dists/$i -maxdepth 2 -type d -name "binary-*" | \
         sed -e "s#$mirrordir/*dists/$i/##" -e 's#/binary-.*##' | tr '\n' " ")
-	echo "deb file:/media/mirror $i $comp" >> $tmp1
+        echo "deb file:/media/mirror $i $comp" >> $tmp1
     done
 
     mount --bind $tmp1 $nfsrootdir/etc/apt/sources.list
     customize_nfsroot
 
     if [ $keep -eq 1 ]; then
-	echo "fai-cd script stopped for 6666 seconds. The filesystem is now available in $tmp."
-	echo "To continue the script and call the cleanup call: pkill -f 'sleep 6666'"
-	sleep_now 2>/dev/null || true
-	echo "Continue cleanup."
+        echo "fai-cd script stopped for 6666 seconds. The filesystem is now available in $tmp."
+        echo "To continue the script and call the cleanup call: pkill -f 'sleep 6666'"
+        sleep_now 2>/dev/null || true
+        echo "Continue cleanup."
     fi
 
     mkiso
@@ -351,22 +351,22 @@ if [ -x "$(which rsync)" ] ; then rsync=1 ; fi
 while getopts "nkfhHg:bBG:m:C:u:" opt ; do
     case "$opt" in
         C)  cdir=$OPTARG ;;
-	f)  forceremoval=1 ;;
-	h)  usage ;;
-	H)  hidedirs="" ;;
-	g)  grub_config="$OPTARG" ;;
-	k)  keep=1 ;;
-	m)  mirrordir="$OPTARG" ;;
-	n)  makeiso=0 ;;
-	b)  burn=1 ;;
-	B)  bootonly=1 ;;
-	G)  grub_version="$OPTARG" ;;
-	u)  usbdir="$OPTARG"
-	    makeusb=1
-	    makeiso=0
-	    [ $rsync -eq 0 -a -e $usbdir/live ] && die 11 "Please remove $usbdir/live. Aborting."
-	    ;;
-	?)  usage ;;
+        f)  forceremoval=1 ;;
+        h)  usage ;;
+        H)  hidedirs="" ;;
+        g)  grub_config="$OPTARG" ;;
+        k)  keep=1 ;;
+        m)  mirrordir="$OPTARG" ;;
+        n)  makeiso=0 ;;
+        b)  burn=1 ;;
+        B)  bootonly=1 ;;
+        G)  grub_version="$OPTARG" ;;
+        u)  usbdir="$OPTARG"
+            makeusb=1
+            makeiso=0
+            [ $rsync -eq 0 -a -e $usbdir/live ] && die 11 "Please remove $usbdir/live. Aborting."
+            ;;
+        ?)  usage ;;
     esac
 done
 shift $(($OPTIND - 1))
@@ -415,13 +415,13 @@ NFSROOT="$NFSROOT/live/filesystem.dir"
 
 if [ -z "$grub_config" ]; then
     if [ $bootonly -eq 1 ]; then
-	grub_config="/usr/share/fai/menu.lst" # default for boot-only CD
+        grub_config="/usr/share/fai/menu.lst" # default for boot-only CD
     else
-	grub_config="$cfdir/menu.lst" # set default if undefined
+        grub_config="$cfdir/menu.lst" # set default if undefined
     fi
 
     if [ "$grub_version" -eq 2 ]; then
-	grub_config="$cfdir/grub.cfg" # set default if undefined
+        grub_config="$cfdir/grub.cfg" # set default if undefined
     fi
 fi
 
diff --git a/bin/fai-class b/bin/fai-class
--- a/bin/fai-class
+++ b/bin/fai-class
@@ -1,6 +1,5 @@
 #! /bin/bash
 
-# $Id$
 #*********************************************************************
 #
 # fai-class - determine all classes a host belongs to
@@ -47,13 +46,13 @@ addclass() {
 
     # append classes to a file
     while read line ; do
-	case $line in
-	\#*) ;; # strip comments
-	  *) debugmsg "Adding class $line"
-	     for class in $line ; do
-		 echo $class >> $filename
-	     done
-	esac
+        case $line in
+        \#*) ;; # strip comments
+          *) debugmsg "Adding class $line"
+             for class in $line ; do
+                 echo $class >> $filename
+             done
+        esac
     done
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -63,9 +62,9 @@ fc_check_status() {
     st=$2
 
     if [ $st -eq 0 ]; then
-	res="OK."
+        res="OK."
     else
-	res="FAILED with exit code $st."
+        res="FAILED with exit code $st."
     fi
     # put result in the log file and write to stdout
     printf "%-20s $res\n" $cmd | tee -a $LOGDIR/status.log
@@ -75,14 +74,14 @@ usage() {
 
     ex=$1
     cat <<-EOF
-	fai-class  Copyright (C) 2002-2009 Thomas Lange
+        fai-class  Copyright (C) 2002-2009 Thomas Lange
 
-	Usage: fai-class [OPTION] DIRECTORY CLASSFILE
-	Define classes using files and scripts in DIRECTORY
+        Usage: fai-class [OPTION] DIRECTORY CLASSFILE
+        Define classes using files and scripts in DIRECTORY
 
-	Executes scripts in DIRECTORY starting with two digits.
-	The standard output of these scripts are names of classes which
-	are written to CLASSFILE.
+        Executes scripts in DIRECTORY starting with two digits.
+        The standard output of these scripts are names of classes which
+        are written to CLASSFILE.
 EOF
     exit $ex
 }
@@ -92,8 +91,8 @@ testclass() {
     # test if some classes are define multiple times
     duplicate=$(sort $filename | uniq -dc)
     if [ -n "$duplicate" ]; then
-	echo "$0: WARNING. Following classes are defined multiple times: $duplicate"
-	exit 2
+        echo "$0: WARNING. Following classes are defined multiple times: $duplicate"
+        exit 2
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -109,7 +108,7 @@ setup() {
         T) ctest=1 ;;
         t) LOGDIR=$OPTARG; export LOGDIR ;;
         *) usage 1 ;;
-	esac
+        esac
     done
     shift $(($OPTIND - 1))
     [ -z "$2" ] || [ -n "$3" ] && usage 1
@@ -117,16 +116,16 @@ setup() {
     classdir=$1
     filename=$2
     cd $classdir || {
-	echo "$0: Can't change dir to $classdir."
-	exit 99
+        echo "$0: Can't change dir to $classdir."
+        exit 99
     }
     if [ -s $filename ]; then
-	verbosemsg "$filename exists. Renaming to $filename.bak"
-	mv $filename $filename.bak
+        verbosemsg "$filename exists. Renaming to $filename.bak"
+        mv $filename $filename.bak
     fi
     if [ -z "$LOGDIR" ]; then
-	verbosemsg "Setting LOGDIR to default value /tmp/fai"
-	LOGDIR=/tmp/fai; export LOGDIR
+        verbosemsg "Setting LOGDIR to default value /tmp/fai"
+        LOGDIR=/tmp/fai; export LOGDIR
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -153,26 +152,26 @@ for f in $scripts ; do
     [ -f $f ] || continue # skip sockets, pipes, symlinks
     debugmsg "File $f found."
     if [ ! -x $f ]; then
-	echo "Warning: File $f is not executable, so it's not used for defining classes."
-	continue
+        echo "Warning: File $f is not executable, so it's not used for defining classes."
+        continue
     fi
     classes=$(cat $filename)
     export classes
     case $f in
-	*~|*.bak) debugmsg "Skipping backup file $f" ;;
-	*.source)
-	    verbosemsg "Executing $classdir/$f."
-	    # this script can define $newclasses
-	    newclasses=
-	    . $f
-	    fc_check_status $f $?
-	    echo $newclasses | addclass ;; 
-	*)
-	    verbosemsg "Executing $classdir/$f."
-	    classes=$($f </dev/null)
-	    fc_check_status $f $?
-	    echo $classes | addclass
-	    ;;
+        *~|*.bak) debugmsg "Skipping backup file $f" ;;
+        *.source)
+            verbosemsg "Executing $classdir/$f."
+            # this script can define $newclasses
+            newclasses=
+            . $f
+            fc_check_status $f $?
+            echo $newclasses | addclass ;; 
+        *)
+            verbosemsg "Executing $classdir/$f."
+            classes=$($f </dev/null)
+            fc_check_status $f $?
+            echo $classes | addclass
+            ;;
     esac
 done
 
@@ -183,17 +182,17 @@ done
 if [ -f $LOGDIR/additional-classes ]; then
     cat $LOGDIR/additional-classes | addclass
     if [ "$debug" ]; then
-	mv $LOGDIR/additional-classes $LOGDIR/additional-classes.used
+        mv $LOGDIR/additional-classes $LOGDIR/additional-classes.used
     else
         # remove the file after it was used. Do not use the same file more than once.
-	rm -f $LOGDIR/additional-classes
+        rm -f $LOGDIR/additional-classes
     fi
 fi
 
 # add all classes which are listed in a file with the hostname
 if [ -f "$HOSTNAME" ]; then
-	verbosemsg "Using classes from file $classdir/$HOSTNAME"
-	grep -v "^#" $HOSTNAME | addclass
+        verbosemsg "Using classes from file $classdir/$HOSTNAME"
+        grep -v "^#" $HOSTNAME | addclass
 fi
 
 echo ${ADDCLASSES//,/ } | addclass
diff --git a/bin/fai-make-nfsroot b/bin/fai-make-nfsroot
--- a/bin/fai-make-nfsroot
+++ b/bin/fai-make-nfsroot
@@ -1,6 +1,5 @@
 #! /bin/bash
 
-# $Id$
 #*********************************************************************
 #
 # fai-make-nfsroot -- create nfsroot directory and add additional packages
@@ -33,11 +32,11 @@
 usage() {
 
     cat <<-EOF
-	Copyright (C) 1999-2012 Thomas Lange
+        Copyright (C) 1999-2012 Thomas Lange
 
-	Usage: fai-make-nfsroot [OPTIONS]
+        Usage: fai-make-nfsroot [OPTIONS]
   Create an NFSROOT for FAI.
-	Read the man pages pages fai-make-nfsroot(8).
+        Read the man pages pages fai-make-nfsroot(8).
 EOF
     exit 0
 }
@@ -179,10 +178,10 @@ call_verbose() {
 
     if [ "$verbose" ]; then
         "$@"
-	return $?
+        return $?
     else
-	"$@" > /dev/null
-	return $?
+        "$@" > /dev/null
+        return $?
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -191,9 +190,9 @@ setup_ssh() {
     # nothing to do if no ssh is available in nfsroot
     [ -f $NFSROOT/usr/bin/ssh ] || return 0
     if [ $sshpreserve = 1 ]; then
-	tar -C $NFSROOT -xf $tmptar
-	rm $tmptar
-	return 0
+        tar -C $NFSROOT -xf $tmptar
+        rm $tmptar
+        return 0
     fi
 
     mkdir -p -m 700 $NFSROOT/root/.ssh
@@ -201,11 +200,11 @@ setup_ssh() {
         loguserhome=$(eval "cd ~$LOGUSER 2>/dev/null && pwd;true")
         [ -f $loguserhome/.ssh/known_hosts ] && cp $loguserhome/.ssh/known_hosts $NFSROOT/root/.ssh/known_hosts
         [ -d $loguserhome/.ssh ] && {
-	    [ -f $loguserhome/.ssh/id_dsa ] &&
-	       cp -p $loguserhome/.ssh/id_dsa* $NFSROOT/root/.ssh/
-	    [ -f $loguserhome/.ssh/id_rsa ] &&
-	       cp -p $loguserhome/.ssh/id_rsa* $NFSROOT/root/.ssh/
-	}
+            [ -f $loguserhome/.ssh/id_dsa ] &&
+               cp -p $loguserhome/.ssh/id_dsa* $NFSROOT/root/.ssh/
+            [ -f $loguserhome/.ssh/id_rsa ] &&
+               cp -p $loguserhome/.ssh/id_rsa* $NFSROOT/root/.ssh/
+        }
     fi
 
     # enable root login
@@ -250,18 +249,18 @@ call_debootstrap() {
     echo "Calling debootstrap $1 $NFSROOT $2"
     LC_ALL=C call_verbose debootstrap $FAI_DEBOOTSTRAP_OPTS $1 $NFSROOT $2
     if [ $? -ne 0 ]; then
-	echo "ERROR: debootstrap did not complete successfully."
-	echo "This is mostly caused by a broken mirror."
-	echo "Please check your mirror or use an official mirror."
-	[ "$verbose" ] || echo "Call fai-make-nfsroot -v for better debugging."
-	exit 10
+        echo "ERROR: debootstrap did not complete successfully."
+        echo "This is mostly caused by a broken mirror."
+        echo "Please check your mirror or use an official mirror."
+        [ "$verbose" ] || echo "Call fai-make-nfsroot -v for better debugging."
+        exit 10
     fi
 
     if [ ! -f $NFSROOT/usr/bin/apt-get ]; then
-	echo "No apt-get executable available inside the NFSROOT."
-	echo "Maybe debootstrap did not finish successfully. Aborting."
-	[ "$verbose" ] || echo "Call fai-make-nfsroot -v for better debugging."
-	exit 11
+        echo "No apt-get executable available inside the NFSROOT."
+        echo "Maybe debootstrap did not finish successfully. Aborting."
+        [ "$verbose" ] || echo "Call fai-make-nfsroot -v for better debugging."
+        exit 11
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -277,17 +276,17 @@ add_etc_hosts_entries() {
 
     local line
     for eth in $ips; do
-	line=$(getent hosts $eth || true)
-	if [ -n "$line" ] ; then
-	  ainsl -v $NFSROOT/etc/hosts "$line"
+        line=$(getent hosts $eth || true)
+        if [ -n "$line" ] ; then
+          ainsl -v $NFSROOT/etc/hosts "$line"
         else
-	  echo "Warning: no hostname for $eth found, not adding to /etc/hosts."
+          echo "Warning: no hostname for $eth found, not adding to /etc/hosts."
         fi
     done
 
     if [ -f /etc/resolv.conf ]; then
-	cp -Lp $v /etc/resolv.conf $NFSROOT/etc/resolv.conf-installserver
-	cp -Lp $v /etc/resolv.conf $NFSROOT/etc/resolv.conf # this is needed during fai-make-nfsroot
+        cp -Lp $v /etc/resolv.conf $NFSROOT/etc/resolv.conf-installserver
+        cp -Lp $v /etc/resolv.conf $NFSROOT/etc/resolv.conf # this is needed during fai-make-nfsroot
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -298,13 +297,13 @@ create_base() {
     $ROOTCMD apt-get clean
     rm -f $NFSROOT/etc/resolv.conf $NFSROOT/etc/hostname $NFSROOT/etc/udev/rules.d/70-persistent-net.rules
     if [ $usexz -eq 0 ]; then
-	echo "Creating base.tgz"
-	tar --one-file-system -C $NFSROOT -cf - --exclude var/tmp/base.tgz --exclude 'var/lib/apt/lists/*_*' . | gzip > $NFSROOT/var/tmp/base.tgz
+        echo "Creating base.tgz"
+        tar --one-file-system -C $NFSROOT -cf - --exclude var/tmp/base.tgz --exclude 'var/lib/apt/lists/*_*' . | gzip > $NFSROOT/var/tmp/base.tgz
     else
-	echo "Creating base.tar.xz"
-	tar --one-file-system -C $NFSROOT -cf $NFSROOT/var/tmp/base.tar --exclude var/tmp/base.tar --exclude 'var/lib/apt/lists/*_*' .
-	nice xz $NFSROOT/var/tmp/base.tar >/dev/null 2>&1 &
-	xzpid=$!
+        echo "Creating base.tar.xz"
+        tar --one-file-system -C $NFSROOT -cf $NFSROOT/var/tmp/base.tar --exclude var/tmp/base.tar --exclude 'var/lib/apt/lists/*_*' .
+        nice xz $NFSROOT/var/tmp/base.tar >/dev/null 2>&1 &
+        xzpid=$!
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -320,16 +319,16 @@ extract_base() {
       printf "Extracting $basetgz: "
 
       case $basetgz in
-	  *tar.gz|*.tgz)
-	      tar -C $NFSROOT -zxpf "$basetgz" || die 1 "Error while extracting ${basetgz} in ${NFSROOT}."
-	      cp -p "$basetgz" $NFSROOT/var/tmp/base.tar.gz
-	      ;;
+          *tar.gz|*.tgz)
+              tar -C $NFSROOT -zxpf "$basetgz" || die 1 "Error while extracting ${basetgz} in ${NFSROOT}."
+              cp -p "$basetgz" $NFSROOT/var/tmp/base.tar.gz
+              ;;
 
-	    *tar.xz|*.txz)
-	      tar -C $NFSROOT -Jxpf "$basetgz" || die 1 "Error while extracting ${basetgz} in ${NFSROOT}."
-	      cp -p "$basetgz" $NFSROOT/var/tmp/base.tar.xz
-	      ;;
-	  esac
+            *tar.xz|*.txz)
+              tar -C $NFSROOT -Jxpf "$basetgz" || die 1 "Error while extracting ${basetgz} in ${NFSROOT}."
+              cp -p "$basetgz" $NFSROOT/var/tmp/base.tar.xz
+              ;;
+          esac
 
       echo done
     fi
@@ -350,7 +349,7 @@ create_nfsroot() {
     $ROOTCMD dpkg --get-selections | awk '/install$/ {print $1}' > var/tmp/base-pkgs.lis
 
     if [ -n "$FAI_DEBMIRROR" ]; then
-	[ "$verbose" ] && echo "Mounting $FAI_DEBMIRROR to $NFSROOT/$MNTPOINT."
+        [ "$verbose" ] && echo "Mounting $FAI_DEBMIRROR to $NFSROOT/$MNTPOINT."
         mkdir -p $NFSROOT/$MNTPOINT
         mount -o ro,noatime $FAI_DEBMIRROR $NFSROOT/$MNTPOINT || \
                 die 1 "Can't mount $FAI_DEBMIRROR to $NFSROOT/$MNTPOINT."
@@ -397,7 +396,7 @@ EOF
 
     [ -f etc/init/tty1.conf ] || ln -s /usr/sbin/fai etc/init.d/rcS
     if [ -d etc/init ]; then   # if upstart is available
-	find etc/init ! -type d | egrep -v "fai|udev|hostname|mountall|mounted" | xargs -r rm
+        find etc/init ! -type d | egrep -v "fai|udev|hostname|mountall|mounted" | xargs -r rm
     fi
 
     rm -f etc/mdadm/mdadm.conf # remove file which may contain info of the install server
@@ -412,8 +411,8 @@ EOF
     cat >> root/.profile <<-EOF
         PATH=/usr/local/sbin:/usr/local/bin:/usr/lib/fai:/bin:/sbin:/usr/bin:/usr/sbin:
         export PATH
-	. /usr/lib/fai/subroutines
-	set -a
+        . /usr/lib/fai/subroutines
+        set -a
         . /tmp/fai/variables.log 2>/dev/null
 EOF
 
@@ -430,7 +429,7 @@ upgrade_nfsroot() {
     # add any 3rd party repository keys that you may need installed into the NFSROOT
     local f
     for f in `find $cfdir/apt/keys -type f -name *.asc`; do
-	cat $f | $ROOTCMD apt-key add -
+        cat $f | $ROOTCMD apt-key add -
     done
     $ROOTCMD apt-get update
     $ROOTCMD aptitude -Rfy install fai-nfsroot
@@ -485,7 +484,7 @@ fdivert() {
 
     local item
     for item in "$@"; do
-	LC_ALL=C $ROOTCMD dpkg-divert --quiet --add --rename $item
+        LC_ALL=C $ROOTCMD dpkg-divert --quiet --add --rename $item
     done
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -497,7 +496,7 @@ run_hooks() {
 
     echo "Running hooks..."
     for file in $(cd $NFSROOT_HOOKS ;ls 2>/dev/null | egrep '^[[:alnum:]_.-]+$'); do
-	. $NFSROOT_HOOKS/$file
+        . $NFSROOT_HOOKS/$file
     done
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - -
diff --git a/bin/fai-mirror b/bin/fai-mirror
--- a/bin/fai-mirror
+++ b/bin/fai-mirror
@@ -1,6 +1,5 @@
 #! /bin/bash
 
-# $Id$
 #*********************************************************************
 #
 # fai-mirror -- create and manage a partial mirror for FAI
@@ -110,7 +109,7 @@ initialize() {
       -o Dir::State::Lists=$aptcache/var/lib/apt/lists/"
 
     if [ -n "$arch" ]; then
-	aptoptions="$aptoptions -o APT::Architecture=$arch" # add architecture
+        aptoptions="$aptoptions -o APT::Architecture=$arch" # add architecture
     fi
 
     # not needed
@@ -130,16 +129,16 @@ delete_base_packages() {
     local p
 
     if [ ! -f $NFSROOT/var/tmp/base-pkgs.lis ]; then
-	echo "$NFSROOT/var/tmp/base-pkgs.lis not available."
-	echo "Can't remove wasteful packages that are already in base.tgz."
-	return
+        echo "$NFSROOT/var/tmp/base-pkgs.lis not available."
+        echo "Can't remove wasteful packages that are already in base.tgz."
+        return
     fi
     echo "Removing packages that are already included in base.tgz"
     for p in $(cat $NFSROOT/var/tmp/base-pkgs.lis); do
-	if [ -f $archivedir/${p}_*.deb ]; then
-	    [ $verbose -eq 1 ] && echo "deleting package $p"
-	    rm $archivedir/${p}_*.deb
-	fi
+        if [ -f $archivedir/${p}_*.deb ]; then
+            [ $verbose -eq 1 ] && echo "deleting package $p"
+            rm $archivedir/${p}_*.deb
+        fi
     done
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -151,23 +150,23 @@ add_base_packages() {
     # arch dependent packages defined in make-fai-nfsroot
     echo "Adding packages of $cfdir/NFSROOT."
     if [ -f $NFSROOT/var/tmp/packages.nfsroot ]; then
-	plist=$(< $NFSROOT/var/tmp/packages.nfsroot)
-	apt-get $qflag -d $aptoptions -y --force-yes --fix-missing install $plist
+        plist=$(< $NFSROOT/var/tmp/packages.nfsroot)
+        apt-get $qflag -d $aptoptions -y --force-yes --fix-missing install $plist
     else
-	echo "WARNING: $NFSROOT/var/tmp/packages.nfsroot does not exists." >&2
-	echo "Can't add those packages. Maybe the nfsroot is not yet created." >&2
+        echo "WARNING: $NFSROOT/var/tmp/packages.nfsroot does not exists." >&2
+        echo "Can't add those packages. Maybe the nfsroot is not yet created." >&2
     fi
 
     # now use sources.list for debootstrap packages
     echo "$FAI_DEBOOTSTRAP" | awk '{printf "deb %s %s main\n",$2,$1}' | perl -p -e 's/file:/copy:/' > $aptcache/etc/apt/sources.list
     echo "Adding packages from $NFSROOT/var/tmp/base-pkgs.lis"
     if [ -f $NFSROOT/var/tmp/base-pkgs.lis ]; then
-	plist=$(< $NFSROOT/var/tmp/base-pkgs.lis)
-	apt-get $qflag $aptoptions update >/dev/null
-	apt-get $qflag -d $aptoptions -y --force-yes --fix-missing install $plist
+        plist=$(< $NFSROOT/var/tmp/base-pkgs.lis)
+        apt-get $qflag $aptoptions update >/dev/null
+        apt-get $qflag -d $aptoptions -y --force-yes --fix-missing install $plist
     else
-	echo "WARNING: $NFSROOT/var/tmp/base-pkgs.lis does not exists." >&2
-	echo "Can't add those packages. Maybe the nfsroot is not yet created." >&2
+        echo "WARNING: $NFSROOT/var/tmp/base-pkgs.lis does not exists." >&2
+        echo "Can't add those packages. Maybe the nfsroot is not yet created." >&2
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -175,8 +174,8 @@ set-classes() {
 
     # if -c is given, ignore -x
     if [ -n "$cclasses" ]; then
-	export classes=${cclasses//,/ }
-	return
+        export classes=${cclasses//,/ }
+        return
     fi
 
     set +e
@@ -195,16 +194,16 @@ add=1
 qflag=-qq
 while getopts "a:Bvhx:pc:C:m:" opt ; do
     case "$opt" in
-	a) arch=$OPTARG ;;
-	B) add=0 ;;
-	C) cfdir=$OPTARG ;;
-	h) usage ;;
-	x) exclasses="$OPTARG";;
-	c) cclasses="$OPTARG";;
-	m) MAXPACKAGES="$OPTARG";;
-	p) preserve=1;;
-	v) verbose=1; vflag=-v; qflag='';;
-	?) die 1 "Unknown option";;
+        a) arch=$OPTARG ;;
+        B) add=0 ;;
+        C) cfdir=$OPTARG ;;
+        h) usage ;;
+        x) exclasses="$OPTARG";;
+        c) cclasses="$OPTARG";;
+        m) MAXPACKAGES="$OPTARG";;
+        p) preserve=1;;
+        v) verbose=1; vflag=-v; qflag='';;
+        ?) die 1 "Unknown option";;
     esac
 done
 shift $(($OPTIND - 1))
diff --git a/bin/fai-setup b/bin/fai-setup
--- a/bin/fai-setup
+++ b/bin/fai-setup
@@ -1,6 +1,5 @@
 #! /bin/bash
 
-# $Id$
 #*********************************************************************
 #
 # fai-setup -- set up FAI
@@ -37,9 +36,9 @@ options=$@ # all options are also passed to fai-make-nfsroot
 
 while getopts ervC:f:kKV: opt ; do
     case "$opt" in
-	C) cfdir=$OPTARG ;;
-	v) verbose=1 ; v=-v ;;
-	e) expert=1 ;;
+        C) cfdir=$OPTARG ;;
+        v) verbose=1 ; v=-v ;;
+        e) expert=1 ;;
     esac
 done
 
@@ -66,10 +65,10 @@ add_export_line() {
 add_fai_account() {
 
     if id $LOGUSER 2>/dev/null 1>&2 ; then
-	echo Account \$LOGUSER=$LOGUSER  already exists.
-	echo Make sure that all install clients can
-	echo log into this account without a password.
-	return
+        echo Account \$LOGUSER=$LOGUSER  already exists.
+        echo Make sure that all install clients can
+        echo log into this account without a password.
+        return
     fi
 
     adduser --system --disabled-password --home /var/log/fai --gecos "FAI account for log files" --shell /bin/sh  $LOGUSER
@@ -89,53 +88,53 @@ setup_fai_account() {
     loguserhome=$(eval "cd ~$LOGUSER 2>/dev/null && pwd;true")
     sshdir=$loguserhome/.ssh
     if [ -z "$loguserhome" ]; then
-	echo "Can't determine home directory for user $LOGUSER."
-	echo "LOGUSER= $LOGUSER    loguserhome= $loguserhome"
-	exit 8
+        echo "Can't determine home directory for user $LOGUSER."
+        echo "LOGUSER= $LOGUSER    loguserhome= $loguserhome"
+        exit 8
     fi
 
     if [ "$FAI_LOGPROTO" = "ssh" ]; then
-	# set up ssh on the server
-	mkdir -p -m 700 $loguserhome/.ssh
-	
-	#Generating keys for LOGUSER
-	[ -f $sshdir/id_rsa ] || {
-	    ssh-keygen -t rsa -N '' -f $sshdir/id_rsa -C "$LOGUSER@$HOSTNAME"
-	    cat $sshdir/id_rsa.pub >> $sshdir/authorized_keys
-	}
+        # set up ssh on the server
+        mkdir -p -m 700 $loguserhome/.ssh
+        
+        #Generating keys for LOGUSER
+        [ -f $sshdir/id_rsa ] || {
+            ssh-keygen -t rsa -N '' -f $sshdir/id_rsa -C "$LOGUSER@$HOSTNAME"
+            cat $sshdir/id_rsa.pub >> $sshdir/authorized_keys
+        }
 
-	[ -f $sshdir/id_dsa ] || {
-	    ssh-keygen -t dsa -N '' -f $sshdir/id_dsa -C "$LOGUSER@$HOSTNAME"
-	    cat $sshdir/id_dsa.pub >> $sshdir/authorized_keys
-	}
-	
-	#Adding servers keys to known_hosts list of LOGUSER. 
-	#So that installed clients can ssh $LOGUSER@$HOSTNAME without password
-	if [ ! -f $sshdir/known_hosts ]; then
-	    [ -f /etc/ssh/ssh_host_dsa_key.pub ] && DSASERVER=$(sed -e "s/= .*$/=/" /etc/ssh/ssh_host_dsa_key.pub)
-	    [ -f /etc/ssh/ssh_host_rsa_key.pub ] && RSASERVER=$(sed -e "s/= .*$/=/" /etc/ssh/ssh_host_rsa_key.pub )
-	    # determine all IP addresses, and their host names
-	    ips=$(ip addr show up| grep -w inet | cut -d t -f 2 | cut -d ' ' -f 2 | cut -d / -f 1 | grep -v 127.0.0.1)
-	    for ip in $ips; do
-		hname=$(getent hosts $ip| tr -s ' ' ',')
-		: ${hname:=$ip}
-		echo "Adding $hname to known_hosts."
-		[ -z "$DSASERVER" ] || echo "$hname $DSASERVER" >> $sshdir/known_hosts
-		[ -z "$RSASERVER" ] || echo "$hname $RSASERVER" >> $sshdir/known_hosts
-	    done
-	    echo "$sshdir/known_hosts created."
-	else
-	    echo "$sshdir/known_hosts remained unchanged."
-	fi
+        [ -f $sshdir/id_dsa ] || {
+            ssh-keygen -t dsa -N '' -f $sshdir/id_dsa -C "$LOGUSER@$HOSTNAME"
+            cat $sshdir/id_dsa.pub >> $sshdir/authorized_keys
+        }
+        
+        #Adding servers keys to known_hosts list of LOGUSER. 
+        #So that installed clients can ssh $LOGUSER@$HOSTNAME without password
+        if [ ! -f $sshdir/known_hosts ]; then
+            [ -f /etc/ssh/ssh_host_dsa_key.pub ] && DSASERVER=$(sed -e "s/= .*$/=/" /etc/ssh/ssh_host_dsa_key.pub)
+            [ -f /etc/ssh/ssh_host_rsa_key.pub ] && RSASERVER=$(sed -e "s/= .*$/=/" /etc/ssh/ssh_host_rsa_key.pub )
+            # determine all IP addresses, and their host names
+            ips=$(ip addr show up| grep -w inet | cut -d t -f 2 | cut -d ' ' -f 2 | cut -d / -f 1 | grep -v 127.0.0.1)
+            for ip in $ips; do
+                hname=$(getent hosts $ip| tr -s ' ' ',')
+                : ${hname:=$ip}
+                echo "Adding $hname to known_hosts."
+                [ -z "$DSASERVER" ] || echo "$hname $DSASERVER" >> $sshdir/known_hosts
+                [ -z "$RSASERVER" ] || echo "$hname $RSASERVER" >> $sshdir/known_hosts
+            done
+            echo "$sshdir/known_hosts created."
+        else
+            echo "$sshdir/known_hosts remained unchanged."
+        fi
 
-	chmod 0600 $sshdir/authorized_keys
-	echo "$sshdir/authorized_keys created."
+        chmod 0600 $sshdir/authorized_keys
+        echo "$sshdir/authorized_keys created."
     fi
     if [ "$FAI_LOGPROTO" = "rsh" -a ! -f $loguserhome/.rhosts ]; then
-	# use .rhosts authentication
-	echo "+@faiclients root" > $loguserhome/.rhosts
-	chmod go-rwx $loguserhome/.rhosts
-	echo "$loguserhome/.rhosts created."
+        # use .rhosts authentication
+        echo "+@faiclients root" > $loguserhome/.rhosts
+        chmod go-rwx $loguserhome/.rhosts
+        echo "$loguserhome/.rhosts created."
     fi
 
     logusergid=$(id -ng $LOGUSER)
@@ -157,8 +156,8 @@ if [ -n "$LOGUSER" ]; then
     # chown only if cd was successful
     cd $loguserhome
     if [ $? -eq 0 ]; then
-	[ -e .rhosts ] && chown $LOGUSER:$logusergid . .rhosts || true
-	[ -d .ssh ] && chown -R $LOGUSER:$logusergid .ssh || true
+        [ -e .rhosts ] && chown $LOGUSER:$logusergid . .rhosts || true
+        [ -d .ssh ] && chown -R $LOGUSER:$logusergid .ssh || true
     fi
     mkdir -p $TFTPROOT
     chown -R $LOGUSER:$logusergid $TFTPROOT || true
@@ -185,10 +184,10 @@ if [ -z "$expert" ]; then
     fi
     add_export_line $NFSROOT  "$addr(async,ro,no_subtree_check,no_root_squash)"
     if [ -z "$nfsserver" ]; then
-	echo "Could not find the type of your nfs server. Maybe"
-	echo "no nfs server is installed. I can't restart it."
+        echo "Could not find the type of your nfs server. Maybe"
+        echo "no nfs server is installed. I can't restart it."
     else
-	/etc/init.d/$nfsserver reload
+        /etc/init.d/$nfsserver reload
     fi
 fi
 
diff --git a/dev-utils/fai-kvm b/dev-utils/fai-kvm
--- a/dev-utils/fai-kvm
+++ b/dev-utils/fai-kvm
@@ -59,10 +59,10 @@ EOF
 while getopts "hnu:s:m:d:" opt ; do
     case "$opt" in
         n) newdisk=1    ;;
-	u) user=$OPTARG ;;
-	m) ram=$OPTARG ;;
-	s) size=$OPTARG ;;
-	d) disks=$OPTARG ;;
+        u) user=$OPTARG ;;
+        m) ram=$OPTARG ;;
+        s) size=$OPTARG ;;
+        d) disks=$OPTARG ;;
         h) usage;;
         ?) die 1 "Unknown option";;
     esac
@@ -95,7 +95,7 @@ case "$1" in
     pxe) boot_pxe ;;
     faicd) boot_faicd $2 ;;
     *)
-	echo "Missing argument." >&2
-	usage
-	;;
+        echo "Missing argument." >&2
+        usage
+        ;;
 esac
diff --git a/lib/fetch-basefile b/lib/fetch-basefile
--- a/lib/fetch-basefile
+++ b/lib/fetch-basefile
@@ -16,8 +16,8 @@ mount_ramdisk() {
     # put ramdisk on config space and download file
     mount -t tmpfs tmpfs $FAI/basefiles # this makes files from NFS invisible
     if [ $? -eq 1]; then
-	echo "mount ramdisk onto $FAI/basefiles failed." >&2
-	exit 3
+        echo "mount ramdisk onto $FAI/basefiles failed." >&2
+        exit 3
     fi
 }
 
@@ -58,20 +58,20 @@ for c in $revclasses; do
     id="found_$c"  # prepare for indirect variable name
     if [ X${!id} != X ]; then
       # hash lookup succeeded
-	found=1
-	[ $mount = 1 ] && mount_ramdisk
-	cd $FAI/basefiles || exit 3
-	if [ -f ${!id} ]; then
-	    echo "${!id} already exists" >&2
-	    error=1
-	    break
-	fi
+        found=1
+        [ $mount = 1 ] && mount_ramdisk
+        cd $FAI/basefiles || exit 3
+        if [ -f ${!id} ]; then
+            echo "${!id} already exists" >&2
+            error=1
+            break
+        fi
 
-	echo "Downloading $url/${!id}"
+        echo "Downloading $url/${!id}"
       #  wget -nv $url/${!id}    # creates a new file with suffix .1, .2,.. if file already exists. Bad.
-	lftp -e "get $url/${!id};exit" # fails if file already exists. this is nice.
-	error=$?
-	break
+        lftp -e "get $url/${!id};exit" # fails if file already exists. this is nice.
+        error=$?
+        break
     fi
 done
 
diff --git a/lib/get-config-dir b/lib/get-config-dir
--- a/lib/get-config-dir
+++ b/lib/get-config-dir
@@ -1,6 +1,5 @@
 #!/bin/bash
 
-# $Id$
 #
 # (c) 2006 Henning Glawe <glaweh@debian.org>
 # (c) 2009-2011 Thomas Lange  <lange@debian.org>
@@ -13,10 +12,10 @@
 ### END SUBROUTINE INFO
 
 if [ -z "$FAI_CONFIG_SRC" ]; then
-	sendmon "TASKERROR get_fai_dir 21"
-	echo "ERROR: No URL defined for the config space." >&2
-	echo "ERROR: Set \$FAI_CONFIG_SRC or use option -s." >&2
-	exit 21
+        sendmon "TASKERROR get_fai_dir 21"
+        echo "ERROR: No URL defined for the config space." >&2
+        echo "ERROR: Set \$FAI_CONFIG_SRC or use option -s." >&2
+        exit 21
 fi
 
 echo "FAI_CONFIG_SRC is set to $FAI_CONFIG_SRC"
@@ -30,9 +29,9 @@ echo "FAI_CONFIG_SRC is set to $FAI_CONFIG_SRC"
 method=$(expr match "$FAI_CONFIG_SRC" '\([^+]*\).*://')
 
 if [ -z "$method" ]; then
-	sendmon "TASKERROR get_fai_dir 22"
-	echo "Error in get-config-dir: scheme undefined."  >&2
-	exit 24
+        sendmon "TASKERROR get_fai_dir 22"
+        echo "Error in get-config-dir: scheme undefined."  >&2
+        exit 24
     echo
 fi
 
@@ -40,11 +39,11 @@ fi
 
 # run get-config-dir-$method script if it exists
 if which get-config-dir-$method &>/dev/null ; then
-	get-config-dir-$method
+        get-config-dir-$method
 else
-	sendmon "TASKERROR get_fai_dir 22"
-	echo "Error: get-config-dir-"$method "not found"  >&2
-	exit 22
+        sendmon "TASKERROR get_fai_dir 22"
+        echo "Error: get-config-dir-"$method "not found"  >&2
+        exit 22
 fi
 
 if [ $method = "file" ]; then
@@ -54,8 +53,8 @@ fi
 
 ln -sf $FAI /var/run/fai/current_config
 if [ ! -d $FAI/class ]; then
-	echo "WARNING: directory $FAI/class not found."  >&2
-	sendmon "TASKERROR get_fai_dir 23"
-	exit 23
+        echo "WARNING: directory $FAI/class not found."  >&2
+        sendmon "TASKERROR get_fai_dir 23"
+        exit 23
 fi
 exit 0
diff --git a/lib/mkramdisk b/lib/mkramdisk
--- a/lib/mkramdisk
+++ b/lib/mkramdisk
@@ -1,6 +1,5 @@
 #! /bin/bash
 
-# $Id$
 #*********************************************************************
 #
 # mkramdisk -- mount a ramdisk on top of a directory
@@ -21,8 +20,8 @@ mount_ramdisk() {
     local n=
 
     if [ ! -d "$1" ]; then
-	echo "WARNING: $1 is not a directory. Cannot make it writeable." >&2
-	return
+        echo "WARNING: $1 is not a directory. Cannot make it writeable." >&2
+        return
     fi
 
     echo
@@ -95,8 +94,8 @@ fi
 
 for d in $FAI_RAMDISKS; do
     if [ $umount -eq 1 ]; then
-	umount_ramdisk $d
+        umount_ramdisk $d
     else
-	[ -d "$d" ] && mount_ramdisk $d $size $mtab
+        [ -d "$d" ] && mount_ramdisk $d $size $mtab
     fi
 done
