when doing dirinstall -c or -N must be specified (closes: #429554)

diff --git a/bin/fai b/bin/fai
--- a/bin/fai
+++ b/bin/fai
@@ -214,6 +214,12 @@ if [ X$action = Xdirinstall ]; then
 	echo "Please specify a target directory. Aborted"
 	exit 3
     fi
+    if [ $renewclass -eq 0 -a -z "$cmdlineclasses" ]; then
+	echo "Please use -c or -N. Aborted"
+	exit 4
+    fi
+
+
     export NFSROOT=$(source $FAI_ETC_DIR/make-fai-nfsroot.conf; echo $NFSROOT)
     export FAI_DEBOOTSTRAP=$(source $FAI_ETC_DIR/make-fai-nfsroot.conf; echo $FAI_DEBOOTSTRAP)
     export FAI_DEBOOTSTRAP_OPT=$(source $FAI_ETC_DIR/make-fai-nfsroot.conf; echo $FAI_DEBOOTSTRAP_OPT)
