fai: check if make-fai-nfsroot.conf is available if dirinstall is used

diff --git a/bin/fai b/bin/fai
--- a/bin/fai
+++ b/bin/fai
@@ -245,6 +245,11 @@ if [ X$action = Xdirinstall ]; then
     fi
     unset fs
 
+    if [ ! -e $FAI_ETC_DIR/make-fai-nfsroot.conf ]; then
+	echo "$FAI_ETC_DIR/make-fai-nfsroot.conf not found."
+	echo "You may want to install the package fai-server"
+	exit 7
+    fi
     export NFSROOT=$(source $FAI_ETC_DIR/make-fai-nfsroot.conf; echo $NFSROOT)
     export FAI_DEBOOTSTRAP=$(source $FAI_ETC_DIR/make-fai-nfsroot.conf; echo $FAI_DEBOOTSTRAP)
     export FAI_DEBOOTSTRAP_OPTS=$(source $FAI_ETC_DIR/make-fai-nfsroot.conf; echo $FAI_DEBOOTSTRAP_OPTS)
