rename make-fai-nfsroot.conf to nfsroot.conf

diff --git a/bin/fai b/bin/fai
--- a/bin/fai
+++ b/bin/fai
@@ -242,14 +242,14 @@ if [ X$action = Xdirinstall ]; then
     fi
     unset fs
 
-    if [ ! -e $FAI_ETC_DIR/make-fai-nfsroot.conf ]; then
-	echo "$FAI_ETC_DIR/make-fai-nfsroot.conf not found." >&2
+    if [ ! -e $FAI_ETC_DIR/nfsroot.conf ]; then
+	echo "$FAI_ETC_DIR/nfsroot.conf not found." >&2
 	echo "You may want to install the package fai-server" >&2
 	exit 7
     fi
-    export NFSROOT=$(source $FAI_ETC_DIR/make-fai-nfsroot.conf; echo $NFSROOT)
-    export FAI_DEBOOTSTRAP=$(source $FAI_ETC_DIR/make-fai-nfsroot.conf; echo $FAI_DEBOOTSTRAP)
-    export FAI_DEBOOTSTRAP_OPTS=$(source $FAI_ETC_DIR/make-fai-nfsroot.conf; echo $FAI_DEBOOTSTRAP_OPTS)
+    export NFSROOT=$(source $FAI_ETC_DIR/nfsroot.conf; echo $NFSROOT)
+    export FAI_DEBOOTSTRAP=$(source $FAI_ETC_DIR/nfsroot.conf; echo $FAI_DEBOOTSTRAP)
+    export FAI_DEBOOTSTRAP_OPTS=$(source $FAI_ETC_DIR/nfsroot.conf; echo $FAI_DEBOOTSTRAP_OPTS)
 
 fi
 
