fai-diskimage: Error only if unsuccessful

diff --git a/bin/fai-diskimage b/bin/fai-diskimage
--- a/bin/fai-diskimage
+++ b/bin/fai-diskimage
@@ -21,13 +21,17 @@ cleanup() {
     local dir
     for dir in $(mount | awk '{print $3}'| grep $mnt | sort -r); do
 	# try umount several times, because some postinst jobs may still run and use the filesystems
+	local umounted=0
 	for i in {1..15}; do
-            umount $dir >&/dev/null && break
+            if umount $dir >&/dev/null; then
+                umounted=1
+                break
+            fi
             [ $((i % 3)) -eq 0 ] && echo "Waiting for background jobs to finish."
             [ $i -gt 12 ] && echo "Still cannot umount $dir. Will try again."
 	    sleep $i
 	done
-	echo "ERROR: fai-diskimage cannot umount $dir" >&2
+	[ "$umounted" -eq 0 ] && echo "ERROR: fai-diskimage cannot umount $dir" >&2
     done
 
     # call zerofree for ext2/3/4 devices if available
