use zstd instead of gzip

diff --git a/bin/fai-make-nfsroot b/bin/fai-make-nfsroot
--- a/bin/fai-make-nfsroot
+++ b/bin/fai-make-nfsroot
@@ -348,7 +348,7 @@ create_base() {
     $ROOTCMD apt-get clean
     rm -f $NFSROOT/etc/resolv.conf $NFSROOT/etc/hostname $NFSROOT/etc/udev/rules.d/70-persistent-net.rules
     if [ $usexz -eq 0 ]; then
-        echo "Creating base.tar.gz"
+        echo "Creating base.tar.zst"
     else
         echo "Creating base.tar.xz"
     fi
@@ -356,7 +356,7 @@ create_base() {
     if [ $usexz -eq 1 ]; then
         nice xz -q $NFSROOT/var/tmp/base.tar &
     else
-        nice gzip $NFSROOT/var/tmp/base.tar &
+        nice zstd --rm -q -7 -T4 $NFSROOT/var/tmp/base.tar &
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -365,15 +365,17 @@ extract_base() {
     if cd $NFSROOT ; then
       printf "Extracting $basetgz: "
       case $basetgz in
-          *tar.gz|*.tgz)
-              tar --xattrs --acls --xattrs-include=* -C $NFSROOT -zxpf "$basetgz" || die 1 "Error while extracting ${basetgz} in ${NFSROOT}."
-              cp -p "$basetgz" $NFSROOT/var/tmp/base.tar.gz
+          *tar.zst|*.tzst)
+              tar --xattrs --acls --xattrs-include=* -C $NFSROOT --zstd -xpf "$basetgz" || die 1 "Error while extracting ${basetgz} in ${NFSROOT}."
+              cp -p "$basetgz" $NFSROOT/var/tmp/base.tar.zst
               ;;
 
             *tar.xz|*.txz)
               tar --xattrs --acls --xattrs-include=* -C $NFSROOT -Jxpf "$basetgz" || die 1 "Error while extracting ${basetgz} in ${NFSROOT}."
               cp -p "$basetgz" $NFSROOT/var/tmp/base.tar.xz
               ;;
+            *)
+                die 14 "Unknow file name suffix"
           esac
       echo done
     fi
@@ -392,7 +394,7 @@ create_nfsroot() {
       create_base
     fi
     touch .THIS_IS_THE_FAI_NFSROOT
-    # save the list of all packages in the base.tar.gz
+    # save the list of all packages in the base.tar.zst
     $ROOTCMD dpkg --get-selections | awk '/install$/ {print $1}' > var/tmp/base-pkgs.lis
 
     if [ -n "$FAI_DEBMIRROR" ]; then
