use command -v instead of type and which

diff --git a/bin/fai-make-nfsroot b/bin/fai-make-nfsroot
--- a/bin/fai-make-nfsroot
+++ b/bin/fai-make-nfsroot
@@ -276,7 +276,7 @@ call_debootstrap() {
 	fi
     fi
     if [ $_debootstrap = "qemu-debootstrap" ]; then
-	if ! type -P $_debootstrap >/dev/null; then
+	if ! command -v $_debootstrap >&/dev/null; then
 	    die 1 "qemu-debootstrap not found. Please install the package qemu-user-static."
 	fi
     fi
@@ -327,7 +327,7 @@ add_etc_hosts_entries() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 create_base() {
 
-    [ ! -x "$(which debootstrap)" ] && die 1 "Can't find debootstrap command. Aborting."
+    command -v debootstrap >&/dev/null || die 1 "Can't find debootstrap command. Aborting."
     call_debootstrap $FAI_DEBOOTSTRAP
     $ROOTCMD apt-get clean
     rm -f $NFSROOT/etc/resolv.conf $NFSROOT/etc/hostname $NFSROOT/etc/udev/rules.d/70-persistent-net.rules
diff --git a/bin/fai-mirror b/bin/fai-mirror
--- a/bin/fai-mirror
+++ b/bin/fai-mirror
@@ -290,7 +290,7 @@ export NFSROOT
 if [ -n "$csdir" ]; then
     FAI_CONFIGDIR=$csdir # override by -s
 fi
-[ -x "$(which reprepro)" ] || die 8 "reprepro not found. Please install the package."
+command -v reprepro >&/dev/null || die 8 "reprepro not found. Please install the package."
 [ -n "$exclasses" -a -n "$cclasses" ] && die 3 "Options -x and -c not allowed at the same time."
 
 # use first argument if given, use variable mirrordir if not argument was given
