move code to end

diff --git a/bin/fai-sed b/bin/fai-sed
--- a/bin/fai-sed
+++ b/bin/fai-sed
@@ -60,11 +60,6 @@ fi
 
 cmp -s $filename $tmp
 res=$?
-if [ $res -eq 2 ]; then
-    printf " diff error $res. No changes made to $filename\n"
-    exit 2
-fi
-
 if [ $res -eq 0 ]; then
     printf " No changes.\n"
     exit 0
@@ -82,4 +77,9 @@ if [ $res -eq 1 ]; then
 	exit 9
     fi
     exit 0
+fi
+
+if [ $res -eq 2 ]; then
+    printf " diff error $res. No changes made to $filename\n"
+    exit 2
 fi
