print warnings and error messages to stderr

diff --git a/bin/fai-cd b/bin/fai-cd
--- a/bin/fai-cd
+++ b/bin/fai-cd
@@ -66,7 +66,7 @@ die() {
     local e=$1   # first parameter is the exit code
     shift
 
-    echo "ERROR: $@"    # print error message
+    echo "ERROR: $@" >&2   # print error message
     exit $e
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -398,7 +398,7 @@ fi
 : ${cfdir:=/etc/fai}
 cfdir=$(readlink -f $cfdir) # canonicalize path
 if [ ! -d "$cfdir" ]; then
-    echo "$cfdir is not a directory"
+    echo "$cfdir is not a directory" >&2
     exit 6
 fi
 [ "$verbose" ] && echo "Using configuration files from $cfdir"
diff --git a/bin/fai-mirror b/bin/fai-mirror
--- a/bin/fai-mirror
+++ b/bin/fai-mirror
@@ -44,7 +44,7 @@ die() {
     local e=$1   # first parameter is the exit code
     shift
 
-    echo "$@"    # print error message
+    echo "$@" >&2 # print error message
     exit $e
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -154,8 +154,8 @@ add_base_packages() {
 	plist=$(< $NFSROOT/var/tmp/packages.nfsroot)
 	apt-get $qflag -d $aptoptions -y --force-yes --fix-missing install $plist
     else
-	echo "WARNING: $NFSROOT/var/tmp/packages.nfsroot does not exists."
-	echo "Can't add those packages. Maybe the nfsroot is not yet created."
+	echo "WARNING: $NFSROOT/var/tmp/packages.nfsroot does not exists." >&2
+	echo "Can't add those packages. Maybe the nfsroot is not yet created." >&2
     fi
 
     # now use sources.list for debootstrap packages
@@ -166,8 +166,8 @@ add_base_packages() {
 	apt-get $qflag $aptoptions update >/dev/null
 	apt-get $qflag -d $aptoptions -y --force-yes --fix-missing install $plist
     else
-	echo "WARNING: $NFSROOT/var/tmp/base-pkgs.lis does not exists."
-	echo "Can't add those packages. Maybe the nfsroot is not yet created."
+	echo "WARNING: $NFSROOT/var/tmp/base-pkgs.lis does not exists." >&2
+	echo "Can't add those packages. Maybe the nfsroot is not yet created." >&2
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
diff --git a/bin/ftar b/bin/ftar
--- a/bin/ftar
+++ b/bin/ftar
@@ -33,7 +33,7 @@ die() {
     local e=$1   # first parameter is the exit code
     shift
 
-    echo "ftar died with error: $@" # print error message
+    echo "ftar died with error: $@" >&2 # print error message
     exit $e
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
diff --git a/dev-utils/fai-kvm b/dev-utils/fai-kvm
--- a/dev-utils/fai-kvm
+++ b/dev-utils/fai-kvm
@@ -95,7 +95,7 @@ case "$1" in
     pxe) boot_pxe ;;
     faicd) boot_faicd $2 ;;
     *)
-	echo "Missing argument."
+	echo "Missing argument." >&2
 	usage
 	;;
 esac
diff --git a/lib/subroutines b/lib/subroutines
--- a/lib/subroutines
+++ b/lib/subroutines
@@ -226,11 +226,11 @@ call_hook() {
     for cl in $classes; do
 	hfile=$FAI/hooks/$hook.$cl
 	if [ -f $hfile -a ! -x $hfile ]; then
-	    echo "WARNING: Skipping $hfile because it's not executable."
+	    echo "WARNING: Skipping $hfile because it's not executable." >&2
 	    continue
 	fi
 	if [ -f $hfile.source -a ! -x $hfile.source ]; then
-	    echo "WARNING: Skipping $hfile.source because it's not executable."
+	    echo "WARNING: Skipping $hfile.source because it's not executable." >&2
 	    continue
 	fi
 	if [ -x $hfile ]; then
@@ -360,7 +360,7 @@ task_action() {
 		echo "Calling user defined action: $FAI_ACTION"
 		$FAI/hooks/$FAI_ACTION
 	    else
-		echo "ERROR: User defined action $FAI/hooks/$FAI_ACTION not found."
+		echo "ERROR: User defined action $FAI/hooks/$FAI_ACTION not found." >&2
 		sendmon "TASKERROR action 22"
 		task_faiend
 	    fi
@@ -480,7 +480,7 @@ task_tests() {
 	    fi
 	fi
     else
-	echo "WARNING: Subdirectory tests/ not found. No tests run."
+	echo "WARNING: Subdirectory tests/ not found. No tests run." >&2
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -533,7 +533,7 @@ EOF
 	cdromdevice=$(awk '/ name:/ {print $3}' /proc/sys/dev/cdrom/info)
 	chroot $target /tmp/rebootCD $cdromdevice
 	# never reached, because chroot will reboot the machine
-	die "Internal error when calling /tmp/rebootCD."
+	die "Internal error when calling /tmp/rebootCD." >&2
     fi
     umount $FAI_ROOT/proc
     umount -ar
@@ -564,11 +564,11 @@ task_install() {
     task savelog
 
     if [ -f $stamp ]; then
-	echo "Error while executing commands in subshell."
+	echo "Error while executing commands in subshell." >&2
 	echo -n "$stamp was not removed. PID of running process: "
 	cat $stamp
 	sendmon "TASKERROR install 21"
-	die "Please look at the log files in $LOGDIR for errors."
+	die "Please look at the log files in $LOGDIR for errors." >&2
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -631,11 +631,11 @@ task_dirinstall() {
     task savelog
 
     if [ -f $stamp ]; then
-	echo "Error while executing commands in subshell."
+	echo "Error while executing commands in subshell." >&2
 	echo -n "$stamp was not removed. PID of running process: "
 	cat $stamp
 	sendmon "TASKERROR install 21"
-	die "Please look at the log files in $LOGDIR for errors."
+	die "Please look at the log files in $LOGDIR for errors." >&2
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -673,11 +673,11 @@ task_softupdate() {
     umount_csspace
 
     if [ -f $stamp ]; then
-	echo "Error while executing commands in subshell."
+	echo "Error while executing commands in subshell." >&2
 	echo -n "$stamp was not removed. PID of running process: "
 	cat $stamp
 	sendmon "TASKERROR softupdate 21"
-	die "Please look at the log files in $LOGDIR for errors."
+	die "Please look at the log files in $LOGDIR for errors." >&2
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -784,7 +784,7 @@ task_confdir() {
 task_partition() {
 
     if [ X$USE_SETUP_STORAGE = X1 ]; then
-	echo "WARNING: The variable USE_SETUP_STORAGE is not needed any more."
+	echo "WARNING: The variable USE_SETUP_STORAGE is not needed any more." >&2
 	echo "setup-storage is now the default tool for partitioning."
     fi
 
@@ -901,11 +901,11 @@ task_repository () {
     for cl in ${classes:-}; do
 	hfile=$FAI/hooks/$hook.$cl
 	if [ -f $hfile ]; then
-	    echo "WARNING: The task prepareapt is obsolete. It was renamed to task repository. Please rename your hook $hfile to repository.$cl."
+	    echo "WARNING: The task prepareapt is obsolete. It was renamed to task repository. Please rename your hook $hfile to repository.$cl." >&2
 	    continue
 	fi
 	if [ -f $hfile.source ]; then
-	    echo "WARNING: The task prepareapt is obsolete. It was renamed to task repository. Please rename your hook $hfile.source to repository.$cl.source."
+	    echo "WARNING: The task prepareapt is obsolete. It was renamed to task repository. Please rename your hook $hfile.source to repository.$cl.source." >&2
 	    continue
 	fi
     done
@@ -1041,7 +1041,7 @@ task_chboot() {
 	$frsh true >/dev/null 2>&1
 	if [ $? -ne 0 ]; then
 	    task_error 3
-	    echo "WARNING: $frsh failed. Can't call fai-chboot on the install server."
+	    echo "WARNING: $frsh failed. Can't call fai-chboot on the install server." >&2
 	else
 	    if [ -n "$nexttest" ]; then
 		# for test sequences, we want the system to reinstall immediately with
