call genisoimage with -R instead of -r
Quote from a mail:
According to the genisoimage man page the "-r" does what normally would be
consider the sane thing and sets all directories to 555. This makes sense as
most people will want the cdfs to be readable by normal users. The problem is
that cfagent doesn't like it's /var/lib directories to be readable by others
and will not run.
The "-R" tells genisoimage to copy the perms as specified in the source
directory. With this option cfagent runs correctly and all is well.

Me: Another approach would be that the permissions for
/var/lib/cfengine2 are fixed during runtime.

diff --git a/bin/fai-cd b/bin/fai-cd
--- a/bin/fai-cd
+++ b/bin/fai-cd
@@ -236,7 +236,7 @@ mkiso() {
     [ $makeiso -eq 0 ] && return
 
     echo "Writing FAI CD-ROM image to $isoname. This may need some time."
-    genisoimage --iso-level 4 -V "$vname" -A "$aname" -log-file /dev/null -quiet -l -r -J -b "$boot_image" -no-emul-boot -boot-load-size 4 -boot-info-table -o $isoname $tmp || die 12 "genisoimage failed." 
+    genisoimage --iso-level 4 -V "$vname" -A "$aname" -log-file /dev/null -quiet -l -R -J -b "$boot_image" -no-emul-boot -boot-load-size 4 -boot-info-table -o $isoname $tmp || die 12 "genisoimage failed." 
     echo -n "ISO image size and filename: "; du -h $isoname
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - -
