add test if command strings is available, Closes: #769683

diff --git a/bin/fai-cd b/bin/fai-cd
--- a/bin/fai-cd
+++ b/bin/fai-cd
@@ -302,6 +302,8 @@ if [ $makeiso -eq 1 ]; then
     [ -x "$(which xorriso)" ] || die 8 "xorriso not found. Please install package."
 fi
 
+[ -x "$(which strings)" ] || die 8 "command strings not found. Please install package binutils."
+
 # use FAI_ETC_DIR from environment variable
 if [ -n "$FAI_ETC_DIR" -a -z "$cdir" ]; then
     echo "Using environment variable \$FAI_ETC_DIR."
