check if $FAI_CONFIGDIR is valid (closes: #334577)

diff --git a/bin/fai-mirror b/bin/fai-mirror
--- a/bin/fai-mirror
+++ b/bin/fai-mirror
@@ -25,7 +25,7 @@
 # MA 02111-1307, USA.
 #*********************************************************************
 
-version="Version 1.4.2, 23-nov-2005"
+version="Version 1.4.3, 2-dec-2005"
 
 # variables: NFSROOT, FAI_CONFIGDIR
 # NFSROOT_PACKAGES, packages from make-fai-nfsroot.conf
@@ -243,6 +243,8 @@ fi
 if [ -d $mirrordir/pool -o -d $mirrordir/dists ]; then
     die 3 "Please first remove $mirrordir/pool and $mirrordir/dists"
 fi
+
+[ -d $FAI_CONFIGDIR/package_config ] || die 6 "Can't find package config files in $FAI_CONFIGDIR."
 
 initialize
 
