do not run if host uses LVM

diff --git a/bin/fai-diskimage b/bin/fai-diskimage
--- a/bin/fai-diskimage
+++ b/bin/fai-diskimage
@@ -174,6 +174,16 @@ if [ $(id -u) != "0" ]; then
     die 1 "Run this program as root."
 fi
 
+# currently fai-diskimage can't be used if the host contains logical volumes
+set +e
+if [ -f /sbin/lvs ]; then
+    lvs 2>&1 | grep -q 'No volume groups found'
+    if [ $? -eq 1 ]; then
+	die 9 "Currently fai-diskimage can't be run if the host uses logical volumes."
+    fi
+fi
+set -e
+
 # create empty disk image, loop setup, temp mount point
 rm -f $rawname
 qemu-img create $rawname $size
