always use --xattrs --acls, Closes: #881829

diff --git a/bin/fai-make-nfsroot b/bin/fai-make-nfsroot
--- a/bin/fai-make-nfsroot
+++ b/bin/fai-make-nfsroot
@@ -332,7 +332,7 @@ create_base() {
     else
         echo "Creating base.tar.xz"
     fi
-    tar --one-file-system -C $NFSROOT -cf $NFSROOT/var/tmp/base.tar --exclude etc/machine-id --exclude var/tmp/base.tar --exclude 'var/lib/apt/lists/*_*' .
+    tar --xattrs --acls --one-file-system -C $NFSROOT -cf $NFSROOT/var/tmp/base.tar --exclude etc/machine-id --exclude var/tmp/base.tar --exclude 'var/lib/apt/lists/*_*' .
     if [ $usexz -eq 1 ]; then
         nice xz -q $NFSROOT/var/tmp/base.tar &
     else
@@ -350,12 +350,12 @@ extract_base() {
       printf "Extracting $basetgz: "
       case $basetgz in
           *tar.gz|*.tgz)
-              tar -C $NFSROOT -zxpf "$basetgz" || die 1 "Error while extracting ${basetgz} in ${NFSROOT}."
+              tar --xattrs --acls --xattrs-include=* -C $NFSROOT -zxpf "$basetgz" || die 1 "Error while extracting ${basetgz} in ${NFSROOT}."
               cp -p "$basetgz" $NFSROOT/var/tmp/base.tar.gz
               ;;
 
             *tar.xz|*.txz)
-              tar -C $NFSROOT -Jxpf "$basetgz" || die 1 "Error while extracting ${basetgz} in ${NFSROOT}."
+              tar --xattrs --acls --xattrs-include=* -C $NFSROOT -Jxpf "$basetgz" || die 1 "Error while extracting ${basetgz} in ${NFSROOT}."
               cp -p "$basetgz" $NFSROOT/var/tmp/base.tar.xz
               ;;
           esac
