fix package name

diff --git a/bin/fai-cd b/bin/fai-cd
--- a/bin/fai-cd
+++ b/bin/fai-cd
@@ -322,7 +322,7 @@ if [ $bootonly -eq 0 ]; then
 fi
 
 [ $squash_only -eq 1 -o -x "$(which xorriso)" ] || die 8 "xorriso not found. Please install package."
-[ -x "$(which mksquashfs)" ] || die 8 "mksquashfs not found. Please install the package mksquashfs-tools."
+[ -x "$(which mksquashfs)" ] || die 8 "mksquashfs not found. Please install the package squashfs-tools."
 [ -x "$(which strings)" ] || die 8 "command strings not found. Please install package binutils."
 
 # use FAI_ETC_DIR from environment variable
