add option -u, add USB support, means copy the fai-cd data to a directory

diff --git a/bin/fai-cd b/bin/fai-cd
--- a/bin/fai-cd
+++ b/bin/fai-cd
@@ -30,12 +30,13 @@
 #*********************************************************************
 
 set -e 
-version="fai-cd 3.0.1, 13 june 2007"
+version="fai-cd 3.1, 4 august 2007"
 
 forceremoval=0;
 burn=0
 keep=0
 makeiso=1
+makeusb=0
 hidedirs="/usr/share/locale /usr/share/doc /var/lib/apt /var/cache/apt /usr/share/man /var/lib/dpkg/info /media/mirror/aptcache /media/mirror/.apt-move"
 
 # we need FAI_CONFIGDIR, NFSROOT
@@ -153,10 +154,11 @@ EOF
 
     mount --bind $tmp1 $nfsrootdir/etc/apt/sources.list
     customize_nfsroot
+
     if [ $keep -eq 1 ]; then
 	echo "fai-cd script stopped for 6666 seconds. The filesystem is now available in $tmp."
 	echo "To continue the script and call the cleanup call: pkill -f 'sleep 6666'"
-	sleep_now 2>/dev/null
+	sleep_now 2>/dev/null || true
 	echo "Continue cleanup."
     fi
 
@@ -164,6 +166,12 @@ EOF
 	echo "Writing FAI CD-ROM image to $isoname. This may need some time."
 	mkisofs -V "$vname" -A "$aname" -log-file /dev/null -quiet -R -b boot/grub/stage2_eltorito -no-emul-boot -boot-load-size 4 -boot-info-table -o $isoname $tmp || die 12 "mkisofs failed." 
 	echo -n "ISO image size and filename: "; du -h $isoname
+    fi
+
+    if [ $makeusb -eq 1 ]; then
+	# TODO: If usbdir is a device (matches /dev/) mount it
+	echo "Writing FAI data to USB device $usbdir"
+	cp -a $tmp/live $usbdir 2>/dev/null || true
     fi
 
     rm $tmp1
@@ -179,7 +187,7 @@ burniso() {
 # main program
 
 # Parse commandline options
-while getopts "nkfhg:bm:C:" opt ; do
+while getopts "nkfhg:bm:C:u:" opt ; do
     case "$opt" in
         C)  cfdir=$OPTARG ;;
 	f)  forceremoval=1 ;;
@@ -189,6 +197,11 @@ while getopts "nkfhg:bm:C:" opt ; do
 	m)  mirrordir="$OPTARG" ;;
 	n)  makeiso=0 ;;
 	b)  burn=1 ;;
+	u)  usbdir="$OPTARG"
+	    makeusb=1
+	    makeiso=0
+	    [ -e $usbdir/live ] && die 11 "Please remove $usbdir/live. Aborting."
+	    ;;
 	?)  usage ;;
     esac
 done
@@ -202,7 +215,9 @@ isoname=$1
 [ -f "$isoname" ]     && die 3 "Outputfile $isoname already exists. Please remove it or use -f."
 [ $(id -u) != "0" ]   && die 9 "Run this program as root."
 
-[ -x "$(which mkisofs)" ] || die 8 "mkisofs not found. Please install package."
+if [ $makeiso -eq 1 ]; then
+    [ -x "$(which mkisofs)" ] || die 8 "mkisofs not found. Please install package."
+fi
 
 # use FAI_ETC_DIR from environment variable
 if [ -n "$FAI_ETC_DIR" -a -z "$cfdir" ]; then
