add option "--iso-level 4" to mkisofs call (closes: #494443)

diff --git a/bin/fai-cd b/bin/fai-cd
--- a/bin/fai-cd
+++ b/bin/fai-cd
@@ -30,7 +30,7 @@
 #*********************************************************************
 
 set -e 
-version="fai-cd 3.3.4, 31-may-2008"
+version="fai-cd 3.3.5, 10-aug-2008"
 
 forceremoval=0;
 burn=0
@@ -126,7 +126,7 @@ mkiso() {
 
     if [ $makeiso -eq 1 ]; then
 	echo "Writing FAI CD-ROM image to $isoname. This may need some time."
-	mkisofs -V "$vname" -A "$aname" -log-file /dev/null -quiet -R -b boot/grub/stage2_eltorito -no-emul-boot -boot-load-size 4 -boot-info-table -o $isoname $tmp || die 12 "mkisofs failed." 
+	mkisofs --iso-level 4 -V "$vname" -A "$aname" -log-file /dev/null -quiet -R -b boot/grub/stage2_eltorito -no-emul-boot -boot-load-size 4 -boot-info-table -o $isoname $tmp || die 12 "mkisofs failed." 
 	echo -n "ISO image size and filename: "; du -h $isoname
     fi
 }
