add support for foreign architecture

diff --git a/bin/fai-make-nfsroot b/bin/fai-make-nfsroot
--- a/bin/fai-make-nfsroot
+++ b/bin/fai-make-nfsroot
@@ -239,6 +239,7 @@ set_root_pw() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 call_debootstrap() {
 
+    local targetarch hostarch1 hostarch2 _debootstrap
     [ -z "$FAI_DEBOOTSTRAP" ] && die 4 "\$FAI_DEBOOTSTRAP not defined."
 
     # check if NFSROOT directory is mounted with bad options
@@ -248,10 +249,30 @@ call_debootstrap() {
     fi
     local dversion=$(dpkg -l debootstrap | awk '/debootstrap/ {print $3}')
     echo "Creating base system using debootstrap version $dversion"
-    echo "Calling debootstrap $FAI_DEBOOTSTRAP_OPTS $1 $NFSROOT $2"
-    LC_ALL=C call_verbose debootstrap $FAI_DEBOOTSTRAP_OPTS $1 $NFSROOT $2
+
+    # Check if we need cross architecture debootstrap
+    targetarch=$(expr "$FAI_DEBOOTSTRAP_OPTS" : '.*--arch=\([^[:space:]]*\)' || true)
+    hostarch1=$(dpkg --print-architecture)
+    hostarch2=$(dpkg --print-foreign-architectures)
+
+    _debootstrap=qemu-debootstrap
+    if [ -z "$targetarch" ]; then
+	_debootstrap=debootstrap
+    else
+	if [ $targetarch = $hostarch1 -o $targetarch = $hostarch2 ]; then
+	_debootstrap=debootstrap
+	fi
+    fi
+    if [ $_debootstrap = "qemu-debootstrap" ]; then
+	if ! type -P $_debootstrap >/dev/null; then
+	    die 1 "qemu-debootstrap not found. Please install the package qemu-user-static."
+	fi
+    fi
+
+    echo "Calling $_debootstrap $FAI_DEBOOTSTRAP_OPTS $1 $NFSROOT $2"
+    LC_ALL=C call_verbose $_debootstrap $FAI_DEBOOTSTRAP_OPTS $1 $NFSROOT $2
     if [ $? -ne 0 ]; then
-        echo "ERROR: debootstrap did not complete successfully."
+        echo "ERROR: $_debootstrap did not complete successfully."
         echo "This is mostly caused by a broken mirror."
         echo "Please check your mirror or use an official mirror."
         [ X$verbose = X1 ] || echo "Call fai-make-nfsroot -v for better debugging."
@@ -260,7 +281,7 @@ call_debootstrap() {
 
     if [ ! -f $NFSROOT/usr/bin/apt-get ]; then
         echo "No apt-get executable available inside the NFSROOT."
-        echo "Maybe debootstrap did not finish successfully. Aborting."
+        echo "Maybe $_debootstrap did not finish successfully. Aborting."
         [ X$verbose = X1 ] || echo "Call fai-make-nfsroot -v for better debugging."
         exit 11
     fi
