abort if cd fails

diff --git a/bin/ftar b/bin/ftar
--- a/bin/ftar
+++ b/bin/ftar
@@ -6,7 +6,7 @@
 # ftar -- extract tar files using FAI classes
 #
 # This script is part of FAI (Fully Automatic Installation)
-# Copyright (C) 2001-2011 Thomas Lange, lange@informatik.uni-koeln.de
+# Copyright (C) 2001-2012 Thomas Lange, lange@informatik.uni-koeln.de
 # Universitaet zu Koeln
 #
 #*********************************************************************
@@ -48,7 +48,7 @@ extract() {
     fi
 
     if [ $removedir -eq 1 ]; then
-        cd $target/$dir
+        cd $target/$dir || die 4 "ftar ERROR: cd to $target/$dir failed. Aborting."
         [ $PWD = "/" ] && die 3 "ftar WARNING: Will not do recursive removal of directory /"
         rm -rf .* * 2>/dev/null
         removedir=0
@@ -66,7 +66,7 @@ usage() {
     cat <<EOF
 ftar, extract tar files using classes.
 
-   Copyright (C) 2001-2011 by Thomas Lange
+   Copyright (C) 2001-2012 by Thomas Lange
 
 Usage: ftar [OPTION] ... SOURCE
 
