addjust messages

diff --git a/bin/ftar b/bin/ftar
--- a/bin/ftar
+++ b/bin/ftar
@@ -32,7 +32,7 @@ die() {
     local e=$1   # first parameter is the exit code
     shift
 
-    echo "ftar died with error: $@" >&2 # print error message
+    echo "ftar: $@" >&2 # print error message
     exit $e
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -47,8 +47,8 @@ extract() {
     fi
 
     if [ $removedir -eq 1 ]; then
-        cd $target/$dir || die 4 "ftar ERROR: cd to $target/$dir failed. Aborting."
-        [ $PWD = "/" ] && die 3 "ftar WARNING: Will not do recursive removal of directory /"
+        cd $target/$dir || die 4 "ERROR: cd to $target/$dir failed. Aborting."
+        [ $PWD = "/" ] && die 3 "WARNING: Will not do recursive removal of directory /"
         rm -rf .* * 2>/dev/null
         removedir=0
     fi
@@ -142,7 +142,7 @@ if [ $tardone -eq 0 ]; then
         echo "ftar: No matching class found in $fpath"
         exit 0
     else
-        die 1 "ftar: No matching class found in $fpath"
+        die 1 "No matching class found in $fpath"
     fi
 fi
 
