check if debootstrap finished properly (closes: #524369)

diff --git a/bin/make-fai-nfsroot b/bin/make-fai-nfsroot
--- a/bin/make-fai-nfsroot
+++ b/bin/make-fai-nfsroot
@@ -243,7 +243,19 @@ call_debootstrap() {
     local dversion=$(dpkg -l debootstrap | awk '/debootstrap/ {print $3}')
     echo "Creating base system using debootstrap version $dversion"
     echo "Calling debootstrap $1 $NFSROOT $2"
-    yes '' | LC_ALL=C call_verbose debootstrap $FAI_DEBOOTSTRAP_OPTS $1 $NFSROOT $2
+    LC_ALL=C call_verbose debootstrap $FAI_DEBOOTSTRAP_OPTS $1 $NFSROOT $2
+    if [ $? -ne 0 ]; then
+	echo "ERROR: debootstrap did not completed sucsessfully."
+	echo "This is mostly caused by a broken mirror."
+	echo "Please check your mirror or use an official mirror."
+	exit 10
+    fi
+
+    if [ ! -f $NFSROOT/usr/bin/apt-get ]; then
+	echo "No apt-get executable available inside the NFSROOT."
+	echo "Maybe debootstrap did not finished sucsessfully. Aborting."
+	exit 11
+    fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 add_all_host_entries() {
