remove unneeded else

diff --git a/bin/make-fai-nfsroot b/bin/make-fai-nfsroot
--- a/bin/make-fai-nfsroot
+++ b/bin/make-fai-nfsroot
@@ -288,14 +288,14 @@ extract_base() {
 
     if [ ! -r "$basetgz" ] ; then
       die "Specified $basetgz could not be used."
-    else
-       if cd $NFSROOT ; then
-	 printf "Extracting $basetgz: "
-	 tar -C $NFSROOT -zxpf "$basetgz" || die "Error while extracting ${basetgz} in ${NFSROOT}."
-	 cp "$basetgz" $NFSROOT/var/tmp/base.tgz
-	 touch $NFSROOT/.THIS_IS_THE_FAI_NFSROOT
-	 echo done
-       fi
+    fi
+
+    if cd $NFSROOT ; then
+      printf "Extracting $basetgz: "
+      tar -C $NFSROOT -zxpf "$basetgz" || die "Error while extracting ${basetgz} in ${NFSROOT}."
+      cp "$basetgz" $NFSROOT/var/tmp/base.tgz
+      touch $NFSROOT/.THIS_IS_THE_FAI_NFSROOT
+      echo done
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
