add and use die()

diff --git a/bin/mk-data-partition b/bin/mk-data-partition
--- a/bin/mk-data-partition
+++ b/bin/mk-data-partition
@@ -8,6 +8,15 @@
 
 mntdir=/media/data
 
+die() {
+
+    local e=$1   # first parameter is the exit code
+    shift
+
+    echo "$*" >&2 # print error message
+    exit $e
+}
+
 add_p3() {
 
     # $1: filename or device name
@@ -15,8 +24,7 @@ add_p3() {
     local type
 
     if [ -b $2 ]; then
-        echo "Partition 3 already exists on $1"
-        exit 4
+        die 4 "Partition 3 already exists on $1"
     fi
 
     if [ X$fmt = Xexfat ]; then
@@ -28,8 +36,7 @@ add_p3() {
 
     { echo -e "n\np\n3\n\n\n"; sleep 2; echo -e "v\nt\n3\n$type\nw\n"; } | fdisk -w never $1 >/dev/null 2>&1
     if [ "$?" -ne 0 ]; then
-        echo "Cannot add 3th partition to $1. Error code $?"
-        exit 3
+        die 3 "Cannot add 3th partition to $1. Error code $?"
     fi
     udevadm settle --timeout=10
 }
@@ -123,23 +130,19 @@ fi
 filename=$(readlink -f $filename)
 
 if expr "$size" : '^[0-9]\+$' >/dev/null; then
-   echo "Size $size needs a unit like K, M, G, T"
-   exit 5
+   die 5 "Size $size needs a unit like K, M, G, T"
 fi
 
 if [ -n "$1" ] && [ X$copy = X ]; then
-    echo "If you want to copy directories, add -c"
-    exit 3
+    die 3 "If you want to copy directories, add -c"
 fi
 
 if [ $(id -u) != "0" ]; then
-    echo "Run this program as root."
-    exit 2
+    die 2 "Run this program as root."
 fi
 
 if [ ! -b $filename ] && [ ! -f $filename ]; then
-    echo "$filename is neither a device nor an existing file"
-    exit 9
+    die 9 "$filename is neither a device nor an existing file"
 fi
 
 if [ -b $filename ]; then
@@ -158,20 +161,17 @@ if [ -f $filename ]; then
     set +e
     fdisk -l $filename | egrep -q ^${filename}3
     if [ $? -eq 0 ]; then
-        echo "Partition 3 already exists on $filename"
-        exit 5
+        die 5 "Partition 3 already exists on $filename"
     fi
     size=${size:-300M}
     echo "Extend $filename by $size"
     truncate -s +$size $filename
     if [ $? -ne 0 ]; then
-        echo "Cannot extend $filename. Aborting"
-        exit 9
+        die 9 "Cannot extend $filename. Aborting"
     fi
     loop=$(losetup -P -f --show $filename)
     if [ "$?" -ne 0 ]; then
-        echo "Cannot create loop device"
-        exit 5
+        die 5 "Cannot create loop device"
     fi
     trap "losetup -d $loop" EXIT
     part=${loop}p3
