replace if by && or ||, do not use $?

diff --git a/bin/mk-data-partition b/bin/mk-data-partition
--- a/bin/mk-data-partition
+++ b/bin/mk-data-partition
@@ -1,10 +1,12 @@
 #! /bin/bash
 
-# (c) 2023 by Thomas Lange, lange@debian.org
+# (c) 2023-2026 by Thomas Lange, lange@debian.org
 #
 # mk-data-partition  ISO | <USB device>
 # extend an ISO file by size and create a data partition
 # for USB stick the data partition will take the whole size of the USB stick
+
+set -o pipefail
 
 mntdir=/media/data
 
@@ -23,9 +25,7 @@ add_p3() {
     # $2: partition name
     local type
 
-    if [ -b $2 ]; then
-        die 4 "Partition 3 already exists on $1"
-    fi
+    [ -b $2 ] && die 4 "Partition 3 already exists on $1"
 
     if [ X$fmt = Xexfat ]; then
         type=7
@@ -129,17 +129,13 @@ if [ -z "$filename" ]; then
 fi
 filename=$(readlink -f $filename)
 
-if expr "$size" : '^[0-9]\+$' >/dev/null; then
-   die 5 "Size $size needs a unit like K, M, G, T"
-fi
+expr "$size" : '^[0-9]\+$' >/dev/null && die 5 "Size $size needs a unit like K, M, G, T"
 
 if [ -n "$1" ] && [ X$copy = X ]; then
     die 3 "If you want to copy directories, add -c"
 fi
 
-if [ $(id -u) != "0" ]; then
-    die 2 "Run this program as root."
-fi
+[ $(id -u) != "0" ] || die 2 "Run this program as root."
 
 if [ ! -b $filename ] && [ ! -f $filename ]; then
     die 9 "$filename is neither a device nor an existing file"
@@ -159,18 +155,11 @@ if [ -f $filename ]; then
 
     # check if the image already has a 3th partition
     set +e
-    fdisk -l $filename | egrep -q ^${filename}3
-    if [ $? -eq 0 ]; then
-        die 5 "Partition 3 already exists on $filename"
-    fi
+    fdisk -l $filename | egrep -q ^${filename}3 && die 5 "Partition 3 already exists on $filename"
     size=${size:-300M}
     echo "Extend $filename by $size"
-    truncate -s +$size $filename
-    if [ $? -ne 0 ]; then
-        die 9 "Cannot extend $filename. Aborting"
-    fi
-    loop=$(losetup -P -f --show $filename)
-    if [ "$?" -ne 0 ]; then
+    truncate -s +$size $filename || die 9 "Cannot extend $filename. Aborting"
+    if ! loop=$(losetup -P -f --show $filename); then
         die 5 "Cannot create loop device"
     fi
     trap "losetup -d $loop" EXIT
