add test

diff --git a/dev-utils/fai-kvm b/dev-utils/fai-kvm
--- a/dev-utils/fai-kvm
+++ b/dev-utils/fai-kvm
@@ -104,6 +104,9 @@ if [ -z "$1" ]; then
 fi
 
 : ${title:=FAI-kvm-$user}
+if ! [[ $user =~ ^[0-9]+$ ]] ; then
+    die 2 "Error: Option -u needs a number"
+fi
 hex=$(echo $user 16o p | dc)
 diskfile=$diskdir/faitest-disk-$user
 
