abort if bridge device already exists

diff --git a/dev-utils/fai-mk-network b/dev-utils/fai-mk-network
--- a/dev-utils/fai-mk-network
+++ b/dev-utils/fai-mk-network
@@ -58,6 +58,10 @@ mk_tap_devices() {
 
 mk_bridge() {
 
+    if [ -d /sys/class/net/$brname ]; then
+        echo "Bridge $brname already exists. Aborting."
+        exit 4
+    fi
 
     if [ $private -eq 0 ]; then
 	dhclient -r $netdev
