check if brctl is available

diff --git a/dev-utils/fai-mk-network b/dev-utils/fai-mk-network
--- a/dev-utils/fai-mk-network
+++ b/dev-utils/fai-mk-network
@@ -87,6 +87,11 @@ while getopts r opt ; do
 done
 shift $(($OPTIND - 1))
 
+if [ ! -x "$(which brctl)" ]; then
+    echo "brctl not found. Please install bridge-utils."
+    exit 3
+fi
+
 if [ $(id -u) != "0" ]; then
     echo "Run this program as root."
     exit 3
