The base system should better be extracted before we attempt to bind-mount /dev and /proc

diff --git a/patches/grub-in-target b/patches/grub-in-target
--- a/patches/grub-in-target
+++ b/patches/grub-in-target
@@ -9,21 +9,7 @@ Index: trunk/lib/subroutines
 ===================================================================
 --- trunk.orig/lib/subroutines
 +++ trunk/lib/subroutines	
-@@ -421,6 +421,13 @@
- 	sendmon "TASKERROR mountdisks 705"
- 	task_error 705
-     fi
-+    # mount /dev and /proc on target otherwise grub-installer will fail
-+    mount -o bind /dev $FAI_ROOT/dev
-+    task_error 706 $?
-+    if [ ! -e $FAI_ROOT/proc/version ]; then
-+      mount -o bind /proc $FAI_ROOT/proc
-+      task_error 707 $?
-+    fi
- }
- # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- task_configure() {
-@@ -494,6 +501,7 @@
+@@ -494,6 +494,7 @@
  	die "Internal error when calling /tmp/rebootCD."
      fi
      umount $FAI_ROOT/proc
@@ -31,6 +17,20 @@ Index: trunk/lib/subroutines
      umount -ar
      exec reboot -dfi
  }
+@@ -818,6 +819,13 @@
+     [ -f $LOGDIR/crypttab ] && cp -p $LOGDIR/crypttab $FAI_ROOT/etc/crypttab
+     # make /var/lib/dpkg a ramdisk
+     mkramdisk -a
++    # mount /dev and /proc on target otherwise grub-installer will fail
++    mount -o bind /dev $FAI_ROOT/dev
++    task_error 802 $?
++    if [ ! -e $FAI_ROOT/proc/version ]; then
++      mount -o bind /proc $FAI_ROOT/proc
++      task_error 803 $?
++    fi
+ }
+ # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+ ### BEGIN SUBROUTINE INFO
 Index: trunk/examples/simple/files/boot/grub/menu.lst/postinst
 ===================================================================
 --- trunk.orig/examples/simple/files/boot/grub/menu.lst/postinst
