new code for trap ERR, it now saves the maximum value of all errors
In the past the variable error was only set to 1, since a logical OR
was used inside the trap code. Now it compares the actual exit code $?
with the previous value of $error and saves the bigger of both back to $error

diff --git a/scripts/CENTOS/40-install-grub b/scripts/CENTOS/40-install-grub
--- a/scripts/CENTOS/40-install-grub
+++ b/scripts/CENTOS/40-install-grub
@@ -2,7 +2,7 @@
 
 # (c) Michael Goetze, 2011, mgoetze@mgoetze.net
 
-error=0 ; trap "error=$((error|1))" ERR
+error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code
 
 if [ -r $LOGDIR/disk_var.sh ] ; then
 	. $LOGDIR/disk_var.sh
diff --git a/scripts/LAST/50-misc b/scripts/LAST/50-misc
--- a/scripts/LAST/50-misc
+++ b/scripts/LAST/50-misc
@@ -1,8 +1,8 @@
 #! /bin/bash
 
-# copyright Thomas Lange 2001-2007, lange@debian.org
+# copyright Thomas Lange 2001-2011, lange@debian.org
 
-error=0 ; trap "error=$((error|1))" ERR
+error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code
 
 # remove backup files from cfengine, but only if cfengine is installed
 if [ -x /usr/sbin/cfagent ] || [ -x $target/usr/sbin/cfagent ] ; then
