make sure functions are defined, closes: #1063146 if setup-storage is not run in a FAI environment the functions must be defined by sourcing subroutines

diff --git a/lib/fai-disk-info b/lib/fai-disk-info
--- a/lib/fai-disk-info
+++ b/lib/fai-disk-info
@@ -1,4 +1,13 @@
 #! /bin/bash
 
+if ! command -v set_bootstick >&/dev/null; then
+    if [ -f /usr/lib/fai/subroutines ]; then
+        . /usr/lib/fai/subroutines
+    else
+        echo "Cannot find /usr/lib/fai/subroutines"
+        echo "Please install package fai-client"
+    fi
+fi
+
 set_bootstick
 all_disks_and_size | checkdisk $FAI_BOOTSTICK | once_only
