improve message if subroutines are missing.

diff --git a/lib/fai-disk-info b/lib/fai-disk-info
--- a/lib/fai-disk-info
+++ b/lib/fai-disk-info
@@ -4,8 +4,9 @@ if ! command -v set_bootstick >&/dev/null; then
     if [ -f /usr/lib/fai/subroutines ]; then
         . /usr/lib/fai/subroutines
     else
-        echo "Cannot find /usr/lib/fai/subroutines"
-        echo "Please install package fai-client"
+        echo "Cannot find /usr/lib/fai/subroutines" >/dev/stderr
+        echo "Please install package fai-client"    >/dev/stderr
+        exit 99
     fi
 fi
 
