fix indentation

diff --git a/lib/fetch-basefile b/lib/fetch-basefile
--- a/lib/fetch-basefile
+++ b/lib/fetch-basefile
@@ -35,9 +35,9 @@ found=0
 mount=0
 
 while getopts m opt ; do
-        case "$opt" in
+    case "$opt" in
         m) mount=1 ;;
-        esac
+    esac
 done
 #shift $(($OPTIND - 1))
 
@@ -49,8 +49,8 @@ flist=$(lftp -e 'cls;exit' $url 2>/dev/null)
 # value is the complete filename
 for f in $flist; do
   # echo file found: $f
-  base=${f%%.*}   # basename is the class name
-  eval "found_$base=$f"
+    base=${f%%.*}   # basename is the class name
+    eval "found_$base=$f"
 done
 
 # reverse order of classes
@@ -60,28 +60,28 @@ done
 
 # now search for each class, if a basename matches
 for c in $revclasses; do
-  id="found_$c"  # prepare for indirect variable name
-  if [ X${!id} != X ]; then
+    id="found_$c"  # prepare for indirect variable name
+    if [ X${!id} != X ]; then
       # hash lookup succeeded
-      found=1
-      [ $mount = 1 ] && mount_ramdisk
-      cd $FAI/basefiles || exit 3
-      if [ -f ${!id} ]; then
-	  echo "${!id} already exists" >&2
-	  error=1
-	  break
-      fi
+	found=1
+	[ $mount = 1 ] && mount_ramdisk
+	cd $FAI/basefiles || exit 3
+	if [ -f ${!id} ]; then
+	    echo "${!id} already exists" >&2
+	    error=1
+	    break
+	fi
 
-      echo "Downloading $url/${!id}"
+	echo "Downloading $url/${!id}"
       #  wget -nv $url/${!id}    # creates a new file with suffix .1, .2,.. if file already exists. Bad.
-      lftp -e "get $url/${!id};exit" # fails if file already exists. this is nice.
-      error=$?
-      break
-  fi
+	lftp -e "get $url/${!id};exit" # fails if file already exists. this is nice.
+	error=$?
+	break
+    fi
 done
 
 if [ X$found = X0 ]; then
-  echo "No basefile matching a class name was found at $url" >&2
+    echo "No basefile matching a class name was found at $url" >&2
 fi
 
 exit $error
