Support using remote basefiles, even if the basefiles-folder does not exist.

diff --git a/lib/fetch-basefile b/lib/fetch-basefile
--- a/lib/fetch-basefile
+++ b/lib/fetch-basefile
@@ -60,6 +60,8 @@ for c in $revclasses; do
       # hash lookup succeeded
         found=1
         [ $mount = 1 ] && mount_ramdisk
+        # Create folder in case it is not part of the configuration space
+        mkdir -p $FAI/basefiles || echo "Could not create folder $FAI/basefiles" >&2
         cd $FAI/basefiles || exit 3
         if [ -f ${!id} ]; then
             echo "${!id} already exists" >&2
