print errors and warnings to stderr

diff --git a/lib/get-config-dir b/lib/get-config-dir
--- a/lib/get-config-dir
+++ b/lib/get-config-dir
@@ -14,8 +14,8 @@
 
 if [ -z "$FAI_CONFIG_SRC" ]; then
 	sendmon "TASKERROR get_fai_dir 21"
-	echo "ERROR: No URL defined for the config space."
-	echo "ERROR: Set \$FAI_CONFIG_SRC or use option -s."
+	echo "ERROR: No URL defined for the config space." >&2
+	echo "ERROR: Set \$FAI_CONFIG_SRC or use option -s." >&2
 	exit 21
 fi
 
@@ -31,7 +31,7 @@ method=$(expr match "$FAI_CONFIG_SRC" '\([^+]*\).*://')
 
 if [ -z "$method" ]; then
 	sendmon "TASKERROR get_fai_dir 22"
-	echo "Error in get-config-dir: scheme undefined."
+	echo "Error in get-config-dir: scheme undefined."  >&2
 	exit 24
     echo
 fi
@@ -43,7 +43,7 @@ if which get-config-dir-$method &>/dev/null ; then
 	get-config-dir-$method
 else
 	sendmon "TASKERROR get_fai_dir 22"
-	echo "Error: get-config-dir-"$method "not found"
+	echo "Error: get-config-dir-"$method "not found"  >&2
 	exit 22
 fi
 
@@ -54,7 +54,7 @@ fi
 
 ln -sf $FAI /var/run/fai/current_config
 if [ ! -d $FAI/class ]; then
-	echo "WARNING: directory $FAI/class not found."
+	echo "WARNING: directory $FAI/class not found."  >&2
 	sendmon "TASKERROR get_fai_dir 23"
 	exit 23
 fi
diff --git a/lib/get-config-dir-http b/lib/get-config-dir-http
--- a/lib/get-config-dir-http
+++ b/lib/get-config-dir-http
@@ -35,7 +35,7 @@ base=${file%%.*}
 if wget -q -t5 -O $fdir/$file.md5 ${FAI_CONFIG_SRC}.md5; then
    echo "Checksum file $file.md5 successfully downloaded."
 else
-   echo "Checksum file ${FAI_CONFIG_SRC}.md5 failed to download. Aborting."
+   echo "Checksum file ${FAI_CONFIG_SRC}.md5 failed to download. Aborting." >&2
    task_error 881
 fi
 
@@ -46,7 +46,7 @@ task_error 882 $?
 
 # check the md5 sum
 echo -n "MD5 checksum of "
-md5sum -c $file.md5 || echo "checksum mismatch. ERROR."
+md5sum -c $file.md5 || echo "checksum mismatch. ERROR." >&2
 task_error 883 $?
 
 # extraxt the downloaded file using ftar. Therefore define a class
diff --git a/lib/mkramdisk b/lib/mkramdisk
--- a/lib/mkramdisk
+++ b/lib/mkramdisk
@@ -21,7 +21,7 @@ mount_ramdisk() {
     local n=
 
     if [ ! -d "$1" ]; then
-	echo "WARNING: $1 is not a directory. Cannot make it writeable."
+	echo "WARNING: $1 is not a directory. Cannot make it writeable." >&2
 	return
     fi
 
@@ -47,7 +47,7 @@ umount_ramdisk() {
     # test, if a ramdisk is mounted to this directory
     mount | grep -q " $disk type tmpfs"
     if [ $? -eq 1 ]; then
-        echo "$disk is not a mounted ramdisk."
+        echo "$disk is not a mounted ramdisk." >&2
         return
     fi
 
@@ -83,7 +83,7 @@ done
 shift $(($OPTIND - 1))
 
 if [ -n "$FAI_NORAMDISK" ]; then
-    echo "The use of \$FAI_NORAMDISK is now deprecated. Please use \$FAI_RAMDISKS instead."
+    echo "The use of \$FAI_NORAMDISK is now deprecated. Please use \$FAI_RAMDISKS instead." >&2
     exit 99
 fi
 
