minor change in messages

diff --git a/lib/get-config-dir-http b/lib/get-config-dir-http
--- a/lib/get-config-dir-http
+++ b/lib/get-config-dir-http
@@ -45,10 +45,11 @@ wget -q -t 3 $FAI_CONFIG_SRC && echo "done"
 task_error 702 $?
 
 # check the md5 sum
-md5sum -c $file.md5 || echo "Checksum mismatch "
+echo -n "MD5 checksum of "
+md5sum -c $file.md5 || echo "checksum mismatch. ERROR."
 task_error 703 $?
 
 # extraxt the downloaded file using ftar. Therefore define a class
 # with the basename of the file
-echo "extracting config space from $file"
+echo "Extracting config space from $file"
 ftar -c $base -t $FAI -s $fdir .
