get-config-dir-svn: Fix broken-pipe error in SVN URL check

diff --git a/lib/get-config-dir-svn b/lib/get-config-dir-svn
--- a/lib/get-config-dir-svn
+++ b/lib/get-config-dir-svn
@@ -53,14 +53,14 @@ user=
 [ -n "$username" ] && user="--username $username"
 
 if [ -d "$FAI/.svn" ] ; then
-    if [ `svn info $FAI | egrep -m1 -o '://.+'` == "://$svnpath" ]; then
+    if [ `svn info $FAI | grep '^URL:' | egrep -o '://.+'` == "://$svnpath" ]; then
         echo "Updating SVN in $FAI"
         cd $FAI
         svn up $user $pass | grep -v 'Updated to revision' > $LOGDIR/getconf.log
         task_error 701 ${PIPESTATUS[0]}
     else
         echo "$FAI already contains a svn repository, but it is not from $svnurl!" >&2
-        echo "Please delete $FAI manually. Aborting..." >&2
+        echo "Please delete $FAI manually. Fatal error." >&2
         task_error 703
     fi
 else 
