improve error message

diff --git a/lib/get-config-dir b/lib/get-config-dir
--- a/lib/get-config-dir
+++ b/lib/get-config-dir
@@ -14,7 +14,7 @@
 if [ -z "$FAI_CONFIG_SRC" ]; then
         sendmon "TASKERROR get_fai_dir 21"
         echo "ERROR: No URL defined for the config space." >&2
-        echo "ERROR: Set \$FAI_CONFIG_SRC or use option -s." >&2
+        echo "ERROR: Set \$FAI_CONFIG_SRC by using fai-chboot -u or use option -s when calling fai directly." >&2
         exit 21
 fi
 
