replace die call with echo and exit statement, add error message

diff --git a/lib/get-config-dir b/lib/get-config-dir
--- a/lib/get-config-dir
+++ b/lib/get-config-dir
@@ -11,7 +11,8 @@
 
 if [ -z "$FAI_CONFIG_SRC" ]; then
 	sendmon "TASKERROR get_fai_dir 21"
-	die "Error: Provide the URL to obtain the fai config storage in \$FAI_CONFIG_SRC"
+	echo "Error: Provide the URL to obtain the fai config storage in \$FAI_CONFIG_SRC"
+	exit 21
 fi
 
 # extract method to get the config dir
@@ -27,10 +28,14 @@ if which get-config-dir-$method &>/dev/null ; then
 	get-config-dir-$method
 else
 	sendmon "TASKERROR get_fai_dir 22"
-	die "Error: get-config-dir-"$method "not found"
+	echo "Error: get-config-dir-"$method "not found"
+	exit 22
 fi
 
 ln -s $FAI /var/run/fai/current_config
 if [ ! -d $FAI/class ]; then
 	echo "WARNING: directory $FAI/class not found."
+	sendmon "TASKERROR get_fai_dir 23"
+	exit 23
 fi
+exit 0
