add a local variable, still set the global task_error to the maximum error code
before the value of task_error was overwritten by the next task

diff --git a/lib/subroutines b/lib/subroutines
--- a/lib/subroutines
+++ b/lib/subroutines
@@ -198,6 +198,7 @@ task_error() {
 
     [ X$2 = X0 ] && return
     task_error_func=${FUNCNAME[*]}
+    task_local_error=$1
     [ $1 -gt $task_error ] && task_error=$1
     [ $task_error -gt $STOP_ON_ERROR ] && stop_fai_installation
 }
@@ -218,6 +219,7 @@ task() {
 
     local taskname=$1
     shift
+    local task_local_error=0 # the error code set by every task
 
     [ -f $LOGDIR/skip.$taskname ] || call_hook $taskname "$@"
 
@@ -229,14 +231,13 @@ task() {
     else
         echo "Calling task_$taskname"
         sendmon "TASKBEGIN $taskname"
-        task_error=0   # task can set this variable to indicate an error
         task_error_func=''
         taskduration[$taskname]=$SECONDS
         task_$taskname "$@"
         [ $duration -eq 1 ] && echo "Duration of task $taskname: " $(($SECONDS-${taskduration[$taskname]}))"s"
-        sendmon "TASKEND $taskname $task_error"
-        if [ "$task_error" -ne 0 ] ; then
-          echo "Exit code task_$taskname: $task_error" >&2
+        sendmon "TASKEND $taskname $task_local_error"
+        if [ "$task_local_error" -ne 0 ] ; then
+          echo "Exit code task_$taskname: $task_local_error" >&2
         fi
     fi
 }
