print errors and warnings to stderr

diff --git a/lib/subroutines b/lib/subroutines
--- a/lib/subroutines
+++ b/lib/subroutines
@@ -157,7 +157,7 @@ stop_fai_installation() {
 
     # this subroutine should directly stop the installation process
     sendmon "TASKEND $taskname $task_error"
-    echo "Error in task $taskname. Traceback: $task_error_func"
+    echo "Error in task $taskname. Traceback: $task_error_func" >&2
     die "FATAL ERROR. Installation stopped."
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -205,7 +205,7 @@ task() {
         task_$taskname
         sendmon "TASKEND $taskname $task_error"
         if [ "$task_error" -ne 0 ] ; then
-          echo "Exit code task_$taskname: $task_error"
+          echo "Exit code task_$taskname: $task_error" >&2
         fi
     fi
 }
