new order of subroutines as they are called

diff --git a/lib/subroutines b/lib/subroutines
--- a/lib/subroutines
+++ b/lib/subroutines
@@ -315,266 +315,6 @@ call_hook() {
      done
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-task_defvar() {
-
-    local class
-    cd /fai/class
-    for class in $classes ; do
-	if [ -f $class.var ]; then
-	    [ "$verbose" ] && echo "Executing $class.var"
-	    [ "$debug" ] && set -vx
-	    . $class.var </dev/null
-	    [ "$debug" ] && set +vx
-	fi
-    done
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-task_defclass() {
-
-    local newclasses class f
-
-    cd /fai/class || die "No directory /fai/class found. No configuration in $FAI_LOCATION on the install server."
-    echo "Defining classes"
-
-    [ -f $HOSTNAME ] && newclasses=`cat $HOSTNAME`
-    classes="DEFAULT $newclasses"
-
-    # alphabetical sort is important
-    for f in `ls S[0-9]*.{sh,pl}` ; do
-	if [ -x $f -a -f $f ]; then
-	[ "$verbose" ] && echo "Executing $f"
-	case $f in
-	    *.pl) newclasses=`perl $f </dev/null` ;;
-	    *.sh) newclasses=`sh $f </dev/null | grep -v '^#'` ;;
-	esac
-	[ "$debug" ] && echo "newclasses= $newclasses"
-	classes="$classes $newclasses"
-	fi
-    done
-    classes="$classes $HOSTNAME LAST"
-
-    for class in $classes ; do
-	echo $class >> /tmp/FAI_CLASSES
-	revclasses="$class $revclasses"
-    done
-    # revclass is the list of classes in reversed order
-
-    # define classes as: a.b.c.d for cfengine -D
-    # this doesn't work without echo
-    cfclasses=`echo $classes`
-    cfclasses=${cfclasses// /.}
-    [ "$debug" ] && echo "cfclasses: $cfclasses"
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-task_partition() {
-
-    echo "Partitioning local harddisks"
-    setup_harddisks -X > /tmp/format.log 2>&1
-    if [ ! -s $diskvar ]; then
-	cat /tmp/format.log
-	die "Error: $diskvar not found."
-    fi
-    . $diskvar
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-task_mountdisks() {
-
-    [ ! -f /tmp/fstab ] && die "No /tmp/fstab created."
-    mount2dir $FAI_ROOT /tmp/fstab
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-task_extrbase() {
-
-    echo "Unpacking Debian base archive"
-    zcat /var/tmp/base.tgz | tar -C $FAI_ROOT -xpf -
-    # now we can copy fstab
-    [ -f $FAI_ROOT/etc/fstab ] && mv $FAI_ROOT/etc/fstab $FAI_ROOT/etc/fstab.old
-    cp -p /tmp/fstab $FAI_ROOT/etc/fstab
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-task_mirror() {
-
-    # mount debian mirror directory
-    if [ "$FAI_DEBMIRROR" ]; then
-	mkdir -p $FAI_ROOT/$MNTPOINT
-	mount $romountopt $FAI_DEBMIRROR $FAI_ROOT/$MNTPOINT ||
-	    die "Can't mount $FAI_DEBMIRROR"
-    fi
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-task_instsoft() {
-
-    echo "Installing software may take a while"
-    if [ "$debug" ]; then
-	install_packages | tee -a /tmp/software.log
-    elif [ "$verbose" ]; then
-	yes '' | install_packages | tee -a /tmp/software.log
-    else
-	yes '' | install_packages >> /tmp/software.log 2>&1
-    fi
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-prepare_apt() {
-
-    # ftp and http needs resolv.conf in chroot environment, /etc/hosts is useful
-    cp /tmp/etc/resolv.conf /etc/hosts $FAI_ROOT/etc
-    # set hostname in $FAI_ROOT
-    echo -e "$IPADDR\t$HOSTNAME.$DOMAIN $HOSTNAME" >>$FAI_ROOT/etc/hosts
-    cp /etc/apt/* $FAI_ROOT/etc/apt/
-    # some packages must access /proc even in chroot environment
-    mount -t proc proc $FAI_ROOT/proc
-
-    # if libc is upgraded init u is called in chroot environment and
-    #  init will eat up much cpu time
-    mkdivert /sbin/init
-
-    $ROOTCMD apt-get update
-    $ROOTCMD apt-get check
-    [ $? -ne 0 ] && $ROOTCMD apt-get -f -y install </dev/null 
-    $ROOTCMD dpkg -C
-    [ $? -ne 0 ] && yes '' | $ROOTCMD dpkg --configure -a 
-    $ROOTCMD apt-get -f -y --purge remove pcmcia-cs
-    $ROOTCMD apt-get -f -y upgrade </dev/null
-    # update dpkg info which packages are available
-    $ROOTCMD apt-cache dumpavail > /tmp/dumpavail
-    $ROOTCMD dpkg --update-avail /tmp/dumpavail
-    rm -f $FAI_ROOT/tmp/dumpavail
-
-    # fake some programs
-    mkdivert /usr/sbin/xserver-configure
-    mkdivert /etc/init.d/nis
-    mkdivert /sbin/start-stop-daemon
-    cp /sbin/start-stop-daemon $FAI_ROOT/sbin/start-stop-daemon
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-task_updatebase() {
-
-    echo "Updating base"
-    if [ "$debug" ]; then
-	prepare_apt | tee -a /tmp/updatebase.log 2>&1
-    else
-	prepare_apt  > /tmp/updatebase.log 2>&1
-    fi
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-task_savelog() {
-
-    save_log_local
-    save_log_remote
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-task_chboot() {
-
-    # change boot device (local disk or network)
-    [ "$LOGUSER" -a "$TFTPLINK" ] &&
-	$FAI_REMOTESH -l $LOGUSER ${SERVER} \
-	    "cd /boot/fai; rm -f $HOSTNAME; ln -s $TFTPLINK $HOSTNAME"
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-task_sysinfo() {
-
-    local disk
-    # show some system information and save it on the server
-    { 
-    lspci
-    echo "Ethernet cards found: $netdevices"
-    
-    [ -f /proc/scsi/scsi ] && cat /proc/scsi/scsi
-    cat /proc/partitions
-    disk_info
-    for disk in $disklist; do
-	hdparm -iv /dev/$disk
-	fdisk -s /dev/$disk
-	LC_ALL=C file -s /dev/$disk?* | grep -v ": empty"
-    done
-    fdisk -lu
-    echo -n "xserver for graphic card: "; xviddetect -q
-    #si -p -o shm
-    mount_local_disks
-    fstab_mount
-
-    task defclass
-    task defvar
-
-    echo The defined classes are:
-    echo $classes
-    echo The classes are also saved in /tmp/FAI_CLASSES
-
-    load_keymap_consolechars
-    } | tee -a $rcslog  2>&1
-
-    save_dmesg
-    save_log_remote
-    task_faiend
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-task_backup() {
-
-# FAI_BACKUP_LIST contains backup options
-# proposed format: "hda1 hda3 hda12 sda2 '0 0 1 1'"
-#                  list of devices  list of backup levels
-# this subroutine is not yet tested, not yet used
-# It's only an idea how a backup could be made
-    die "make_backup routine not yet used. But you can use the hook backup."
-    local partition
-    mount_local_disks
-    for partition in $SAVE_DEVICES ; do
-	# tar cf - $FAI_ROOT/$partition | $FAI_REMOTESH -l $LOGUSER $SERVER dd if= of=$HOSTNAME.$partition.tar
-	dump 0f $LOGUSER@$SERVER:backup/$HOSTNAME/$partition.dmp $FAI_ROOT/$partition
-    done
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-task_configure() {
-
-# execute scripts; cfengine, shell, perl and expect scripts are known types
-cd /fai/scripts
-
-local class filetype shelldebug
-
-for class in $classes ; do
-if [ -x $class -a -f $class ]; then
-    filetype=`file $class`
-
-    shelldebug=
-    case $filetype in
-	*"Bourne shell script"*)
-	    [ "$debug" ] && shelldebug="sh -x" ;;
-	*"Bourne-Again shell script"*)
-	    [ "$debug" ] && shelldebug="bash -x" ;;
-    esac
-
-    case $filetype in
-
-	*"Bourne shell script"*|*"Bourne-Again shell script"*)
-	    echo "Executing $shelldebug shell: $class"
-	    echo "=====   shell: $class   =====" >> /tmp/shell.log 2>&1
-	    $shelldebug ./$class >> /tmp/shell.log 2>&1
-	;;
-
-	*"cfengine script"*)
-	    echo "Executing cfengine: $class"
-	    echo "=====   cfengine: $class   =====" >> /tmp/cfengine.log 2>&1
-	    ./$class --no-lock -v -f $class -D${cfclasses} >> /tmp/cfengine.log 2>&1
-	;;
-
-	*"perl script"*)
-	    echo "Executing perl: $class"
-	    echo "=====   perl: $class   =====" >> /tmp/perl.log 2>&1
-	    ./$class >> /tmp/perl.log 2>&1
-	;;
-
-	*"expect script"*)
-	    echo "Executing expect: $class"
-	    echo "=====   expect: $class   =====" >> /tmp/expect.log 2>&1
-	    ./$class >> /tmp/expect.log 2>&1
-	;;
-
-	*) echo "File $class has unsupported type $filetype." ;;
-    esac
-fi
-done
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 task_confdir() {
 
     local dnshost
@@ -636,28 +376,6 @@ task_setup() {
     disk_info
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-task_finish() {
-
-    umount -n $FAI_ROOT/proc
-    # undo fake of programs
-    rmdivert /sbin/start-stop-daemon
-    rmdivert /usr/sbin/xserver-configure
-    rmdivert /etc/init.d/nis
-    rmdivert /sbin/init
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-task_faiend() {
-
-    echo "Press <RETURN> to reboot or ctrl-c to execute a shell"
-    # $reboot is a FAI_FLAG
-    [ -z $reboot ] && read
-    echo "Rebooting $HOSTNAME now"
-    cd /
-    sync
-    umount -ar
-    exec reboot -dfi
-}
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 task_action() {
 
     echo "FAI_ACTION: $FAI_ACTION"
@@ -686,5 +404,287 @@ task_action() {
 	    fi
 	    ;;
 	esac
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+task_defclass() {
+
+    local newclasses class f
+
+    cd /fai/class || die "No directory /fai/class found. No configuration in $FAI_LOCATION on the install server."
+    echo "Defining classes"
+
+    [ -f $HOSTNAME ] && newclasses=`cat $HOSTNAME`
+    classes="DEFAULT $newclasses"
+
+    # alphabetical sort is important
+    for f in `ls S[0-9]*.{sh,pl}` ; do
+	if [ -x $f -a -f $f ]; then
+	[ "$verbose" ] && echo "Executing $f"
+	case $f in
+	    *.pl) newclasses=`perl $f </dev/null` ;;
+	    *.sh) newclasses=`sh $f </dev/null | grep -v '^#'` ;;
+	esac
+	[ "$debug" ] && echo "newclasses= $newclasses"
+	classes="$classes $newclasses"
+	fi
+    done
+    classes="$classes $HOSTNAME LAST"
+
+    for class in $classes ; do
+	echo $class >> /tmp/FAI_CLASSES
+	revclasses="$class $revclasses"
+    done
+    # revclass is the list of classes in reversed order
+
+    # define classes as: a.b.c.d for cfengine -D
+    # this doesn't work without echo
+    cfclasses=`echo $classes`
+    cfclasses=${cfclasses// /.}
+    [ "$debug" ] && echo "cfclasses: $cfclasses"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+task_defvar() {
+
+    local class
+    cd /fai/class
+    for class in $classes ; do
+	if [ -f $class.var ]; then
+	    [ "$verbose" ] && echo "Executing $class.var"
+	    [ "$debug" ] && set -vx
+	    . $class.var </dev/null
+	    [ "$debug" ] && set +vx
+	fi
+    done
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+task_partition() {
+
+    echo "Partitioning local harddisks"
+    setup_harddisks -X > /tmp/format.log 2>&1
+    if [ ! -s $diskvar ]; then
+	cat /tmp/format.log
+	die "Error: $diskvar not found."
+    fi
+    . $diskvar
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+task_mountdisks() {
+
+    [ ! -f /tmp/fstab ] && die "No /tmp/fstab created."
+    mount2dir $FAI_ROOT /tmp/fstab
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+task_extrbase() {
+
+    echo "Unpacking Debian base archive"
+    zcat /var/tmp/base.tgz | tar -C $FAI_ROOT -xpf -
+    # now we can copy fstab
+    [ -f $FAI_ROOT/etc/fstab ] && mv $FAI_ROOT/etc/fstab $FAI_ROOT/etc/fstab.old
+    cp -p /tmp/fstab $FAI_ROOT/etc/fstab
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+task_mirror() {
+
+    # mount debian mirror directory
+    if [ "$FAI_DEBMIRROR" ]; then
+	mkdir -p $FAI_ROOT/$MNTPOINT
+	mount $romountopt $FAI_DEBMIRROR $FAI_ROOT/$MNTPOINT ||
+	    die "Can't mount $FAI_DEBMIRROR"
+    fi
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+task_updatebase() {
+
+    echo "Updating base"
+    if [ "$debug" ]; then
+	prepare_apt | tee -a /tmp/updatebase.log 2>&1
+    else
+	prepare_apt  > /tmp/updatebase.log 2>&1
+    fi
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+prepare_apt() {
+
+    # ftp and http needs resolv.conf in chroot environment, /etc/hosts is useful
+    cp /tmp/etc/resolv.conf /etc/hosts $FAI_ROOT/etc
+    # set hostname in $FAI_ROOT
+    echo -e "$IPADDR\t$HOSTNAME.$DOMAIN $HOSTNAME" >>$FAI_ROOT/etc/hosts
+    cp /etc/apt/* $FAI_ROOT/etc/apt/
+    # some packages must access /proc even in chroot environment
+    mount -t proc proc $FAI_ROOT/proc
+
+    # if libc is upgraded init u is called in chroot environment and
+    #  init will eat up much cpu time
+    mkdivert /sbin/init
+
+    $ROOTCMD apt-get update
+    $ROOTCMD apt-get check
+    [ $? -ne 0 ] && $ROOTCMD apt-get -f -y install </dev/null 
+    $ROOTCMD dpkg -C
+    [ $? -ne 0 ] && yes '' | $ROOTCMD dpkg --configure -a 
+    $ROOTCMD apt-get -f -y --purge remove pcmcia-cs
+    $ROOTCMD apt-get -f -y upgrade </dev/null
+    # update dpkg info which packages are available
+    $ROOTCMD apt-cache dumpavail > /tmp/dumpavail
+    $ROOTCMD dpkg --update-avail /tmp/dumpavail
+    rm -f $FAI_ROOT/tmp/dumpavail
+
+    # fake some programs
+    mkdivert /usr/sbin/xserver-configure
+    mkdivert /etc/init.d/nis
+    mkdivert /sbin/start-stop-daemon
+    cp /sbin/start-stop-daemon $FAI_ROOT/sbin/start-stop-daemon
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+task_instsoft() {
+
+    echo "Installing software may take a while"
+    if [ "$debug" ]; then
+	install_packages | tee -a /tmp/software.log
+    elif [ "$verbose" ]; then
+	yes '' | install_packages | tee -a /tmp/software.log
+    else
+	yes '' | install_packages >> /tmp/software.log 2>&1
+    fi
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+task_configure() {
+
+# execute scripts; cfengine, shell, perl and expect scripts are known types
+cd /fai/scripts
+
+local class filetype shelldebug
+
+for class in $classes ; do
+if [ -x $class -a -f $class ]; then
+    filetype=`file $class`
+
+    shelldebug=
+    case $filetype in
+	*"Bourne shell script"*)
+	    [ "$debug" ] && shelldebug="sh -x" ;;
+	*"Bourne-Again shell script"*)
+	    [ "$debug" ] && shelldebug="bash -x" ;;
+    esac
+
+    case $filetype in
+
+	*"Bourne shell script"*|*"Bourne-Again shell script"*)
+	    echo "Executing $shelldebug shell: $class"
+	    echo "=====   shell: $class   =====" >> /tmp/shell.log 2>&1
+	    $shelldebug ./$class >> /tmp/shell.log 2>&1
+	;;
+
+	*"cfengine script"*)
+	    echo "Executing cfengine: $class"
+	    echo "=====   cfengine: $class   =====" >> /tmp/cfengine.log 2>&1
+	    ./$class --no-lock -v -f $class -D${cfclasses} >> /tmp/cfengine.log 2>&1
+	;;
+
+	*"perl script"*)
+	    echo "Executing perl: $class"
+	    echo "=====   perl: $class   =====" >> /tmp/perl.log 2>&1
+	    ./$class >> /tmp/perl.log 2>&1
+	;;
+
+	*"expect script"*)
+	    echo "Executing expect: $class"
+	    echo "=====   expect: $class   =====" >> /tmp/expect.log 2>&1
+	    ./$class >> /tmp/expect.log 2>&1
+	;;
+
+	*) echo "File $class has unsupported type $filetype." ;;
+    esac
+fi
+done
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+task_finish() {
+
+    umount -n $FAI_ROOT/proc
+    # undo fake of programs
+    rmdivert /sbin/start-stop-daemon
+    rmdivert /usr/sbin/xserver-configure
+    rmdivert /etc/init.d/nis
+    rmdivert /sbin/init
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+task_chboot() {
+
+    # change boot device (local disk or network)
+    [ "$LOGUSER" -a "$TFTPLINK" ] &&
+	$FAI_REMOTESH -l $LOGUSER ${SERVER} \
+	    "cd /boot/fai; rm -f $HOSTNAME; ln -s $TFTPLINK $HOSTNAME"
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+task_savelog() {
+
+    save_log_local
+    save_log_remote
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+task_faiend() {
+
+    echo "Press <RETURN> to reboot or ctrl-c to execute a shell"
+    # $reboot is a FAI_FLAG
+    [ -z $reboot ] && read
+    echo "Rebooting $HOSTNAME now"
+    cd /
+    sync
+    umount -ar
+    exec reboot -dfi
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+task_sysinfo() {
+
+    local disk
+    # show some system information and save it on the server
+    { 
+    lspci
+    echo "Ethernet cards found: $netdevices"
+    
+    [ -f /proc/scsi/scsi ] && cat /proc/scsi/scsi
+    cat /proc/partitions
+    disk_info
+    for disk in $disklist; do
+	hdparm -iv /dev/$disk
+	fdisk -s /dev/$disk
+	LC_ALL=C file -s /dev/$disk?* | grep -v ": empty"
+    done
+    fdisk -lu
+    echo -n "xserver for graphic card: "; xviddetect -q
+    #si -p -o shm
+    mount_local_disks
+    fstab_mount
+
+    task defclass
+    task defvar
+
+    echo The defined classes are:
+    echo $classes
+    echo The classes are also saved in /tmp/FAI_CLASSES
+
+    load_keymap_consolechars
+    } | tee -a $rcslog  2>&1
+
+    save_dmesg
+    save_log_remote
+    task_faiend
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+task_backup() {
+
+# FAI_BACKUP_LIST contains backup options
+# proposed format: "hda1 hda3 hda12 sda2 '0 0 1 1'"
+#                  list of devices  list of backup levels
+# this subroutine is not yet tested, not yet used
+# It's only an idea how a backup could be made
+    die "make_backup routine not yet used. But you can use the hook backup."
+    local partition
+    mount_local_disks
+    for partition in $SAVE_DEVICES ; do
+	# tar cf - $FAI_ROOT/$partition | $FAI_REMOTESH -l $LOGUSER $SERVER dd if= of=$HOSTNAME.$partition.tar
+	dump 0f $LOGUSER@$SERVER:backup/$HOSTNAME/$partition.dmp $FAI_ROOT/$partition
+    done
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
