add stop_fai_installation()

diff --git a/lib/subroutines b/lib/subroutines
--- a/lib/subroutines
+++ b/lib/subroutines
@@ -96,6 +96,14 @@ wait_for_jobs() {
     done
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+stop_fai_installation() {
+
+    # this subroutine should directly stop the installation process
+    echo "FATAL ERROR. Installation stopped."
+    echo "Currently I do not know how to stop."
+    exit 9999
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ### BEGIN SUBROUTINE INFO
 # Provides-Var:      $task_error
 # Required-Var:      $task_error
@@ -107,6 +115,7 @@ task_error() {
     [ $1 -eq 0 ] && return
     echo "Error $1. Traceback: ${FUNCNAME[*]}"
     [ $1 -gt $task_error ] && $task_error=$1
+    [ $task_error -gt $STOP_ON_ERROR ] && stop_fai_installation
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ### BEGIN SUBROUTINE INFO
