print error code when stopping installation

diff --git a/lib/subroutines b/lib/subroutines
--- a/lib/subroutines
+++ b/lib/subroutines
@@ -156,7 +156,8 @@ stop_fai_installation() {
 
     # this subroutine should directly stop the installation process
     sendmon "TASKEND $taskname $task_error"
-    echo "Error in task $taskname. Traceback: $task_error_func" >&2
+    echo "Error in task $taskname. Code: $task_error" >&2
+    echo "Traceback: $task_error_func" >&2
     die "FATAL ERROR. Installation stopped."
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
