add fdie() subroutine

diff --git a/lib/subroutines b/lib/subroutines
--- a/lib/subroutines
+++ b/lib/subroutines
@@ -5,7 +5,7 @@
 # subroutines -- useful subroutines for FAI
 #
 # This script is part of FAI (Fully Automatic Installation)
-# (c) 2000-2013 by Thomas Lange, lange@informatik.uni-koeln.de
+# (c) 2000-2014 by Thomas Lange, lange@informatik.uni-koeln.de
 # Universitaet zu Koeln
 # (c) 2001-2005 by Henning Glawe, glaweh@physik.fu-berlin.de
 # Freie Universitaet Berlin
@@ -30,6 +30,15 @@
 
 # source this file, then you have these function available in the shell
 
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+fdie() {
+
+    local e=$1   # first parameter is the exit code
+    shift
+
+    echo "$@" >&2 # print error message
+    exit $e
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 die() {
 
