new code for trap ERR, it now saves the maximum value of all errors
In the past the variable error was only set to 1, since a logical OR
was used inside the trap code. Now it compares the actual exit code $?
with the previous value of $error and saves the bigger of both back to $error

diff --git a/examples/simple/scripts/DEBIAN/30-interface b/examples/simple/scripts/DEBIAN/30-interface
--- a/examples/simple/scripts/DEBIAN/30-interface
+++ b/examples/simple/scripts/DEBIAN/30-interface
@@ -1,6 +1,6 @@
 #! /bin/bash
 
-error=0 ; trap "error=$((error|1))" ERR
+error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code
 
 if ifclass DHCPC && [ $FAI_ACTION != "softupdate" ]
 then
