tab -> spaces

diff --git a/basefiles/mk-basefile b/basefiles/mk-basefile
--- a/basefiles/mk-basefile
+++ b/basefiles/mk-basefile
@@ -36,29 +36,29 @@ setarch() {
 
     l32=
     if [ X$1 = Xi386 ]; then
-	l32=linux32
+        l32=linux32
     fi
 }
 
 check() {
 
     if [ `id -u` != 0 ]; then
-	echo "You must be root to create chroots."
-	exit 1
+        echo "You must be root to create chroots."
+        exit 1
     fi
     mknod $xtmp/test-dev-null c 1 3
     if [ $? -eq 1 ]; then
-	echo "Cannot create device files on $xtmp, aborting."
-	echo "Perhaps this directory is mounted with option nodev."
-	rm -rf $xtmp
-	exit 1
+        echo "Cannot create device files on $xtmp, aborting."
+        echo "Perhaps this directory is mounted with option nodev."
+        rm -rf $xtmp
+        exit 1
     fi
     echo test > $xtmp/test-dev-null
     if [ $? -eq 1 ]; then
-	echo "Cannot create device files on $xtmp, aborting."
-	echo "Perhaps this directory is mounted with option nodev."
-	rm -rf $xtmp
-	exit 1
+        echo "Cannot create device files on $xtmp, aborting."
+        echo "Perhaps this directory is mounted with option nodev."
+        rm -rf $xtmp
+        exit 1
     fi
     rm -f $xtmp/test-dev-null
 }
@@ -112,8 +112,8 @@ cleanup-rinse() {
 
     rm -f $xtmp/etc/resolv.conf $xtmp/post
     if [ -d $xtmp/etc/yum.repos.d/orig ]; then
-	mv $xtmp/etc/yum.repos.d/orig/* $xtmp/etc/yum.repos.d/
-	rm -rf $xtmp/etc/yum.repos.d/orig
+        mv $xtmp/etc/yum.repos.d/orig/* $xtmp/etc/yum.repos.d/
+        rm -rf $xtmp/etc/yum.repos.d/orig
     fi
 }
 
@@ -199,9 +199,9 @@ tmpdir=/var/tmp
 
 while getopts zJd: opt ; do
     case "$opt" in
-	d) tmpdir=$OPTARG ;;
-	z) zip="gzip -9"; ext=tar.gz ;;
-	J) zip="xz -8" ext=tar.xz ;;
+        d) tmpdir=$OPTARG ;;
+        z) zip="gzip -9"; ext=tar.gz ;;
+        J) zip="xz -8" ext=tar.xz ;;
     esac
 done
 shift $(($OPTIND - 1))
