print errors and warnings to stderr

diff --git a/scripts/LAST/50-misc b/scripts/LAST/50-misc
--- a/scripts/LAST/50-misc
+++ b/scripts/LAST/50-misc
@@ -31,7 +31,7 @@ if ifclass DEBIAN ; then
 fi
 
 lskernels=$(echo $target/boot/vmlinu*)
-[ -f ${lskernels%% *} ] || echo "ERROR: No kernel was installed. Have a look at shell.log"
+[ -f ${lskernels%% *} ] || echo "ERROR: No kernel was installed. Have a look at shell.log" >&2
 # copy sources.list
 fcopy -i /etc/apt/sources.list
 
