chdir to $classdir in the very beginning

diff --git a/scripts/fai-class b/scripts/fai-class
--- a/scripts/fai-class
+++ b/scripts/fai-class
@@ -27,7 +27,7 @@
 # 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 #*********************************************************************
 
-version="version 1.0.3, 07-dec-2002"
+version="version 1.1, 10-dec-2002"
 
 # import variables: $LOGDIR $verbose $debug
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -86,7 +86,7 @@ testclass() {
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-fsetup() {
+setup() {
 
     # parse options, test and set some basic variables
 
@@ -105,10 +105,10 @@ fsetup() {
 
     classdir=$1
     filename=$2
-    if [ ! -d $classdir ]; then
-	echo "$0: $classdir is not a directory."
+    cd $classdir || {
+	echo "$0: Can't change dir to $classdir."
 	exit 99
-    fi
+    }
     if [ -s $filename ]; then
 	verbosemsg "$filename exists. Renaming to $filename.bak"
 	mv $filename $filename.bak
@@ -121,45 +121,38 @@ fsetup() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # main program
-fsetup "$@"
-verbosemsg "Defining classes."
+setup "$@"
+verbosemsg "$0: Defining classes."
 
 echo DEFAULT | addclass
 
+# define classes by executing scripts
 # alphabetical sort is important
 if [ "$debug" ]; then
-    scripts=`cd $classdir ; ls [0-9][0-9]*`
+    scripts=`ls [0-9][0-9]*`
 else
-    scripts=`cd $classdir ; ls [0-9][0-9]* 2>/dev/null`
+    scripts=`ls [0-9][0-9]* 2>/dev/null`
 fi
 debugmsg "Scripts found: $scripts"
 
 for f in $scripts ; do
-    [ -f $classdir/$f ] || continue # skip sockets, pipes, symlinks
+    [ -f $f ] || continue # skip sockets, pipes, symlinks
     debugmsg "File $f found."
-    if [ ! -x $classdir/$f ]; then
+    if [ ! -x $f ]; then
 	echo "File $f is not executable, so it's not used for defining classes."
 	continue
     fi
     verbosemsg "Executing $classdir/$f."
     case $f in
-#	*.pl) perl $f </dev/null | addclass ;;
-#	*.sh) sh   $f </dev/null | addclass ;;
+	*~|*.bak) echo "Skipping backup file $f" ;;
 	*.source)
 	    # this script can define $newclasses
 	    newclasses=
-	    . $classdir/$f
+	    . $f
 	    echo $newclasses | addclass ;; 
-	*~|*.bak) echo "Skipping backup file $f" ;;
-	*) $classdir/$f </dev/null | addclass ;;
+	*) $f </dev/null | addclass ;;
     esac
 done
-
-# add all classes which are listed in a file with the hostname
-if [ -f "$HOSTNAME" ]; then
-	verbosemsg "Using classes from file $HOSTNAME"
-	cat $HOSTNAME | addclass
-fi
 
 # $LOGDIR should not be writable by everybody
 # scripts can also write additional classes to a file, if they
@@ -169,6 +162,12 @@ if [ -f $LOGDIR/additional-classes ]; then
     cat $LOGDIR/additional-classes | addclass
     rm -f $LOGDIR/additional-classes
     # remove the file after it was used. Do not use the same file more than once.
+fi
+
+# add all classes which are listed in a file with the hostname
+if [ -f "$HOSTNAME" ]; then
+	verbosemsg "Using classes from file $HOSTNAME"
+	cat $HOSTNAME | addclass
 fi
 
 # now add the hostname (the only class in lowercase) and LAST to
