bug fixed: chown -R only if loguserhome is set and is can change to this directory this bug changed the owner off ALL files on my notebook to fai :-(

diff --git a/scripts/fai-setup b/scripts/fai-setup
--- a/scripts/fai-setup
+++ b/scripts/fai-setup
@@ -56,6 +56,16 @@ add_export_line() {
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 add_fai_account() {
 
+    # get the home dir of a user in a variable; do not exit when set -e is used
+    # loguserhome is unset if $LOGUSER does not exists
+    # this is not a evil hack, it's a very clever piece of code
+    loguserhome=`eval "cd ~$LOGUSER 2>/dev/null && pwd;true"`
+    if [ -z "$loguserhome" ]; then
+	echo "Can't determine home directory for user $LOGUSER."
+	echo "LOGUSER= $LOGUSER    loguserhome= $loguserhome"
+	exit 8
+    fi
+
     if id $LOGUSER 2>/dev/null 1>&2 ; then
 	echo Account \$LOGUSER=$LOGUSER  already exists.
 	echo Make sure, that all install clients can
@@ -67,23 +77,14 @@ add_fai_account() {
     # there's a bug when the encrypted password is !, so change it to *
     perl -pi.bak -e "s#^$LOGUSER:.:(.+):/bin/false#$LOGUSER:*:\1:/bin/bash#" /etc/passwd
 
-    # get the home dir of a user in a variable; do not exit when set -e is used
-    # loguserhome is unset if $LOGUSER does not exists
-    # this is not a evil hack, it's a very clever piece of code
-    loguserhome=`eval "cd ~$LOGUSER 2>/dev/null && pwd;true"`
-    if [ -z "$loguserhome" ]; then
-	echo "Can't determine home directory for user $LOGUSER."
-	echo "LOGUSER= $LOGUSER    loguserhome= $loguserhome"
-	exit 8
-    fi
-
     if [ $FAI_REMOTESH = "ssh" -o $FAI_REMOTECP = "scp" ]; then
 	# we must set up ssh on the server
 	mkdir -p -m 700 $loguserhome/.ssh
 	ssh-keygen -N '' -f $loguserhome/.ssh/identity -C "$LOGUSER@$HOST"
     	cat $loguserhome/.ssh/identity.pub >> $loguserhome/.ssh/authorized_keys
 	chmod 0700 $loguserhome/.ssh/authorized_keys
-	chown -R $LOGUSER $loguserhome/.ssh
+	# chown only if cd was successful
+	cd $loguserhome && chown -R $LOGUSER .ssh
 	echo "$loguserhome/.ssh/authorized_keys created."
     fi
     if [ $FAI_REMOTESH = "rsh" -o $FAI_REMOTECP = "rcp" ]; then
@@ -104,7 +105,7 @@ add_fai_account
 echo Creating FAI nfsroot can take a long time and will
 echo need more than 100MB disk space in $NFSROOT.
 make-fai-nfsroot
-chown -R $LOGUSER:$logusergid $loguserhome/
+cd $loguserhome && chown -R $LOGUSER:$logusergid .
 
 if [ -z "$FAI_CONFIGDIR" ]; then
     echo "FAI_CONFIGDIR not set in /etc/fai.conf."
