give error message when not finished correcltyl; add bad_exit()

diff --git a/scripts/make-fai-nfsroot b/scripts/make-fai-nfsroot
--- a/scripts/make-fai-nfsroot
+++ b/scripts/make-fai-nfsroot
@@ -40,6 +40,7 @@ if [ `id -u` -ne 0 ]; then
     exit 9
 fi
 
+merror="properly."
 while getopts rvf: opt ; do
     case "$opt" in
         v) verbose=1 ;;
@@ -79,6 +80,14 @@ conffile=$NFSROOT/etc/rcS_fai.conf
 export DEBIAN_FRONTEND=noninteractive
 
 trap "umount_dirs" EXIT
+trap "bad_exit" ERR
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+bad_exit() {
+
+    merror="with errors."
+    echo "An error occured during make-fai-nfsroot."
+    echo "Please fix the error or try make-fai-nfsroot -v"
+}
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 die() {
 
@@ -397,5 +406,5 @@ else
     echo "No kernel modules available in nfsroot."
 fi
 
-echo make-fai-nfsroot finished.
+echo "make-fai-nfsroot finished $merror."
 exit 0
