add variable $DO_INIT_TASKS, add code for softupdate support

diff --git a/scripts/rcS_fai b/scripts/rcS_fai
--- a/scripts/rcS_fai
+++ b/scripts/rcS_fai
@@ -30,11 +30,10 @@
 
 export PATH=/usr/local/sbin:/usr/local/bin:/usr/lib/fai:/bin:/sbin:/usr/bin:/usr/sbin:
 # some variables
-FAI_VERSION=FAIVERSIONSTRING
-stamp=/tmp/FAI_INSTALLATION_IN_PROGRESS
+export FAI_VERSION=FAIVERSIONSTRING
+stamp=/var/run/fai/FAI_INSTALLATION_IN_PROGRESS
 romountopt="-o async,noatime,nolock,ro,actimeo=1800"
 fstab=fstab  # Solaris uses vfstab
-lpipe=/tmp/logfifo
 
 # the type of operating system (linux, sunos)
 oclass=$(uname -s | tr /a-z/ /A-Z/)
@@ -60,6 +59,7 @@ fai_init() {
     local sub osname
     set -a # now export all variables
 
+    umask 022
     # read fai.conf
     # linux dir
     [ -f /etc/fai/fai.conf ] && . /etc/fai/fai.conf
@@ -82,18 +82,36 @@ fai_init() {
     [ -f $sub ] && . $sub
     [ -f $sub-$OS_TYPE ] && . $sub-$OS_TYPE
 
+    [ -f "$stamp" ] && {
+       echo "$0 already running, aborting"
+       exit 1
+    }
+
+    # HG: are we called as an init substitute ?
+    [ "$0" = "/etc/init.d/rcS" ] && DO_INIT_TASKS=1
+
     DEBIAN_FRONTEND=noninteractive
     # local disks are mounted to $FAI_ROOT
-    [ -z "$FAI_ROOT" ] && FAI_ROOT=/tmp/target
+    if [ -z "$FAI_ROOT" ] ; then
+      [ "$DO_INIT_TASKS" ] && FAI_ROOT=/tmp/target || FAI_ROOT=/
+    fi
     # executed command in the environment of the new system
     ROOTCMD="chroot $FAI_ROOT"
     # no chroot needed
     [ "$FAI_ROOT" = '/' ] && ROOTCMD=
+
+    # Solaris has already a writable /tmp directory
+    [ "$oclass" = LINUX -a "$DO_INIT_TASKS" ] && create_ramdisk
+    unset oclass
+
     # directory where temporary log files are stored
     # set default value if nothing is set in fai.conf
-    [ -z "$LOGDIR" ] && LOGDIR=/tmp/fai
-    mkdir -p $LOGDIR
-
+    if [ -z "$LOGDIR" ]; then
+	LOGDIR=/tmp/fai
+	mkdir -p $LOGDIR
+    fi
+    [ "$DO_INIT_TASKS" ] || LOGDIR=$(mktemp -t -d fai.XXXXXX)
+    
     # several log files
     diskvar=$LOGDIR/disk_var.sh
     moduleslog=$LOGDIR/modules.log
@@ -103,8 +121,11 @@ fai_init() {
     files=$FAI/files
     target=$FAI_ROOT
 
-    umask 022
-    trap 'echo "Now rebooting";faireboot' INT QUIT
+    if [ "$DO_INIT_TASKS" ]; then
+        trap 'echo "Now rebooting";faireboot' INT QUIT ;
+    else
+        trap "echo 'Aborted';rm -f $stamp" INT QUIT ;
+    fi
 
     # if HOST was specified on the commandline, set hostname to it
     eval_cmdline
@@ -116,23 +137,26 @@ fai_init() {
     fi
 
     if [ X$OS_TYPE = Xlinux ]; then
-	grep -q '[[:space:]]sysfs' /proc/filesystems && mount -t sysfs sysfs /sys
 	osname='Debian GNU/Linux'
-	ifup lo
-	[ -x /sbin/portmap ] && /sbin/portmap
-	mount -t devpts devpts /dev/pts
-	# add other options for nfs mount of /dev/root to root-path in dhcpd.conf
-	mount -o remount,noatime,ro /dev/root /
-	cat /proc/kmsg >/dev/tty4 &
+	if [ "$DO_INIT_TASKS" ]; then
+	    grep -q '[[:space:]]sysfs' /proc/filesystems && mount -t sysfs sysfs /sys
+	    ifup lo
+	    [ -x /sbin/portmap ] && /sbin/portmap
+	    mount -t devpts devpts /dev/pts
+	    # add other options for nfs mount of /dev/root to root-path in dhcpd.conf
+	    mount -o remount,noatime,ro /dev/root /
+	    cat /proc/kmsg >/dev/tty4 &
+	fi
     fi
+# XXX: raussschmeissen!
     if [ X$OS_TYPE = Xsunos ]; then
 	osname='Sun Solaris'
     fi
 
     # set red color, but not on sparc
     case $HOSTTYPE in
-	sparc*) ;;
-	*) test -e /.nocolorlogo || echo -ne "\ec\e[1;31m" ;;
+	sparc*|powerpc*) ;;
+	*)  test -e /.nocolorlogo || echo -ne "\ec\e[1;31m" ;;
     esac
 
     prcopyleft | tee -a $rcslog
@@ -148,6 +172,18 @@ fai_init() {
     save_dmesg
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+usage() {
+    cat <<EOF
+    Usage:
+        $0 [options] [action]
+       
+    Options:
+       -v|--verbose      display more information during the update
+       -h|--help         display this help message
+EOF
+    exit 0
+}
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 fstart() {
 
     # these tasks can define variables, that are needed later
@@ -155,24 +191,48 @@ fstart() {
     task setup
     task defclass
     task defvar
-    load_keymap_consolechars
+    [ "$DO_INIT_TASKS" ] && load_keymap_consolechars
     set_disk_info
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 # Main routine
-# callarg=$1
 
-# Solaris has already a writable /tmp directory
-[ "$oclass" = LINUX ] && create_ramdisk
-unset oclass
+# Parse commandline options
+TEMP=$(getopt -o hv --long help,verbose -n "$0" -- "$@")
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+# Note the quotes around `$TEMP': they are essential!
+eval set -- "$TEMP"
+
+while true ; do
+    case "$1" in
+        -h|--help)
+	    shift
+	    usage
+            ;;
+	-v|--verbose)
+	    shift
+	    verbose=1
+	    ;;
+        --) 
+            shift
+            break
+            ;;
+         *)
+            echo "$0: command line parsing error ! $@"
+            exit 1
+            ;;
+    esac
+done
 
 fai_init
 
+lpipe=$LOGDIR/logfifo
 mkfifo $lpipe
 tee -a $rcslog < $lpipe &
 # in bash &> redirect stdout and stderr to file
 fstart &> $lpipe
 rm $lpipe
+unset lpipe
 sleep 1 # wait for tee to complete. One second should be ok
 
 # old code
@@ -189,7 +249,9 @@ sleep 1 # wait for tee to complete. One second should be ok
 # if you want to recall rcS_fai
 # [ -n $callarg ] && FAI_ACTION=$callarg
 
+# override FAI_ACTION if a command line argument is given
+[ "$1" ] && FAI_ACTION=$1
+
 task action 2>&1 | tee -a $rcslog
 
-# normally this is never reached
-echo "End of rcS_fai"
+echo "End of $0"
