set error, if no kernel was installed

diff --git a/examples/simple/scripts/LAST/50-misc b/examples/simple/scripts/LAST/50-misc
--- a/examples/simple/scripts/LAST/50-misc
+++ b/examples/simple/scripts/LAST/50-misc
@@ -51,7 +51,10 @@ fi
 
 if [ $FAI_ACTION = "install" ]; then
     lskernels=$(echo $target/boot/vmlinu*)
-    [ -f ${lskernels%% *} ] || echo "ERROR: No kernel was installed. Have a look at shell.log" >&2
+    if [ ! -f ${lskernels%% *} ]; then
+	echo "ERROR: No kernel was installed. Have a look at shell.log" >&2
+	error=1
+    fi
 fi
 
 # copy sources.list
